In [1]:
import pandas as pd
import os

In [2]:
def list_csv_files(directory):
    csv_files = [file for file in os.listdir(directory) if file.endswith('.csv')]
    return csv_files

all_directory = 'c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Glucose_prediction_2026/Compare_Experiments/2026-01-23/2/Diatrend_fix_BGL_limit/csv_performance/report/'
all_csv_files = list_csv_files(all_directory)

def merge_csv_files(directory):
    csv_files = list_csv_files(directory)
    merged_df = pd.DataFrame()

    for file in csv_files:
        file_path = os.path.join(directory, file)
        df = pd.read_csv(file_path)
        df['file_name'] = file
        merged_df = pd.concat([merged_df, df], ignore_index=True)
    
    return merged_df



df_results = merge_csv_files(all_directory)
df_results = df_results.round(2)

df_results

,Range,A,B,C,D,E,A + B,RMSE,MSE,MAE,MAPE,file_name
0,ENTIRE,73.00 ± 1.45,23.98 ± 0.87,0.40 ± 0.12,2.60 ± 0.71,0.02 ± 0.01,96.98 ± 0.76,35.69 ± 1.34,1275.03 ± 95.63,25.95 ± 1.01,0.16 ± 0.01,metrics_performance_by_range_RMSE_CNN_H2_metri...
1,TBR_2,3.08 ± 2.79,0.00 ± 0.00,0.00 ± 0.00,95.60 ± 2.17,1.32 ± 0.65,3.08 ± 2.79,62.43 ± 7.03,3937.01 ± 894.28,57.68 ± 6.74,1.27 ± 0.14,metrics_performance_by_range_RMSE_CNN_H2_metri...
2,TBR_1,1.21 ± 0.67,0.00 ± 0.00,0.00 ± 0.00,97.43 ± 0.30,1.37 ± 0.56,1.21 ± 0.67,48.91 ± 3.85,2403.88 ± 378.64,43.55 ± 3.01,0.70 ± 0.05,metrics_performance_by_range_RMSE_CNN_H2_metri...
3,TIR,67.97 ± 1.82,31.47 ± 1.80,0.56 ± 0.19,0.00 ± 0.00,0.00 ± 0.00,99.44 ± 0.19,29.76 ± 1.14,886.49 ± 68.13,21.84 ± 0.82,0.18 ± 0.01,metrics_performance_by_range_RMSE_CNN_H2_metri...
4,TAR_1,80.66 ± 1.49,18.07 ± 1.40,0.34 ± 0.14,0.93 ± 0.15,0.00 ± 0.00,98.73 ± 0.21,35.17 ± 1.40,1238.15 ± 98.19,25.63 ± 1.18,0.12 ± 0.01,metrics_performance_by_range_RMSE_CNN_H2_metri...
5,TAR_2,81.98 ± 2.54,14.82 ± 1.78,0.06 ± 0.02,3.14 ± 0.80,0.00 ± 0.00,96.80 ± 0.79,47.65 ± 3.62,2281.17 ± 352.20,35.94 ± 2.78,0.12 ± 0.01,metrics_performance_by_range_RMSE_CNN_H2_metri...
6,ENTIRE,58.73 ± 2.45,36.03 ± 1.62,1.01 ± 0.23,4.11 ± 0.85,0.12 ± 0.05,94.76 ± 0.94,49.06 ± 2.48,2412.23 ± 245.33,36.86 ± 1.99,0.23 ± 0.02,metrics_performance_by_range_RMSE_CNN_H4_metri...
7,TBR_2,0.00 ± 0.00,0.00 ± 0.00,0.00 ± 0.00,91.26 ± 5.39,8.74 ± 5.39,0.00 ± 0.00,92.86 ± 11.78,8733.36 ± 2241.12,87.64 ± 10.52,1.93 ± 0.22,metrics_performance_by_range_RMSE_CNN_H4_metri...
8,TBR_1,0.01 ± 0.02,0.00 ± 0.00,0.00 ± 0.00,92.95 ± 2.92,7.03 ± 2.93,0.01 ± 0.02,76.19 ± 6.57,5839.78 ± 1022.68,70.59 ± 5.39,1.13 ± 0.08,metrics_performance_by_range_RMSE_CNN_H4_metri...
9,TIR,53.49 ± 2.48,44.79 ± 2.45,1.72 ± 0.39,0.00 ± 0.00,0.00 ± 0.00,98.28 ± 0.39,40.15 ± 1.61,1613.74 ± 130.22,30.48 ± 1.10,0.26 ± 0.01,metrics_performance_by_range_RMSE_CNN_H4_metri...
10,TAR_1,70.67 ± 2.23,26.85 ± 2.00,0.44 ± 0.20,2.04 ± 0.22,0.00 ± 0.00,97.52 ± 0.34,42.02 ± 1.95,1768.56 ± 164.20,32.27 ± 1.68,0.15 ± 0.01,metrics_performance_by_range_RMSE_CNN_H4_metri...
11,TAR_2,60.30 ± 2.91,29.62 ± 1.43,0.01 ± 0.01,10.07 ± 1.91,0.00 ± 0.00,89.92 ± 1.90,72.34 ± 4.46,5249.20 ± 655.08,58.15 ± 3.73,0.19 ± 0.01,metrics_performance_by_range_RMSE_CNN_H4_metri...
12,ENTIRE,83.50 ± 0.85,15.01 ± 0.73,0.13 ± 0.03,1.34 ± 0.36,0.02 ± 0.00,98.51 ± 0.38,26.72 ± 0.94,714.87 ± 49.61,19.15 ± 0.76,0.12 ± 0.00,metrics_performance_by_range_RMSE_Linear_H2_me...
13,TBR_2,55.78 ± 11.21,0.00 ± 0.00,0.00 ± 0.00,43.83 ± 10.84,0.39 ± 0.46,55.78 ± 11.21,33.65 ± 6.74,1168.90 ± 487.74,26.65 ± 5.02,0.59 ± 0.11,metrics_performance_by_range_RMSE_Linear_H2_me...
14,TBR_1,33.99 ± 2.52,0.00 ± 0.00,0.00 ± 0.00,65.74 ± 2.45,0.27 ± 0.10,33.99 ± 2.52,27.40 ± 2.87,757.45 ± 155.01,21.44 ± 1.83,0.34 ± 0.03,metrics_performance_by_range_RMSE_Linear_H2_me...
15,TIR,78.66 ± 1.37,21.18 ± 1.35,0.17 ± 0.05,0.00 ± 0.00,0.00 ± 0.00,99.83 ± 0.05,23.40 ± 1.10,548.61 ± 51.18,16.96 ± 0.84,0.14 ± 0.01,metrics_performance_by_range_RMSE_Linear_H2_me...
16,TAR_1,89.10 ± 0.92,10.36 ± 0.84,0.13 ± 0.05,0.36 ± 0.07,0.04 ± 0.01,99.46 ± 0.11,27.27 ± 1.13,744.67 ± 61.48,19.22 ± 0.89,0.09 ± 0.00,metrics_performance_by_range_RMSE_Linear_H2_me...
17,TAR_2,92.42 ± 1.03,6.67 ± 0.82,0.04 ± 0.01,0.87 ± 0.22,0.00 ± 0.00,99.09 ± 0.22,33.48 ± 2.02,1124.45 ± 139.98,24.86 ± 1.41,0.08 ± 0.00,metrics_performance_by_range_RMSE_Linear_H2_me...
18,ENTIRE,63.44 ± 2.02,32.57 ± 1.32,0.75 ± 0.18,3.13 ± 0.76,0.11 ± 0.03,96.02 ± 0.83,43.75 ± 1.96,1916.95 ± 171.74,32.63 ± 1.52,0.20 ± 0.01,metrics_performance_by_range_RMSE_Linear_H4_me...
19,TBR_2,7.92 ± 4.80,0.00 ± 0.00,0.00 ± 0.00,87.78 ± 4.27,4.30 ± 2.32,7.92 ± 4.80,68.29 ± 11.03,4760.84 ± 1531.71,59.32 ± 9.70,1.30 ± 0.20,metrics_performance_by_range_RMSE_Linear_H4_me...
20,TBR_1,4.45 ± 1.00,0.00 ± 0.00,0.00 ± 0.00,91.64 ± 1.77,3.91 ± 1.78,4.45 ± 1.00,58.29 ± 6.63,3433.19 ± 780.48,49.89 ± 5.41,0.80 ± 0.08,metrics_performance_by_range_RMSE_Linear_H4_me...
21,TIR,55.78 ± 1.89,43.01 ± 1.83,1.21 ± 0.30,0.00 ± 0.00,0.00 ± 0.00,98.79 ± 0.30,37.18 ± 1.56,1383.96 ± 115.32,28.27 ± 1.08,0.23 ± 0.01,metrics_performance_by_range_RMSE_Linear_H4_me...
22,TAR_1,75.47 ± 2.29,22.55 ± 2.07,0.44 ± 0.17,1.42 ± 0.18,0.11 ± 0.03,98.03 ± 0.30,40.35 ± 2.11,1632.06 ± 170.71,29.74 ± 1.78,0.14 ± 0.01,metrics_performance_by_range_RMSE_Linear_H4_me...
23,TAR_2,71.53 ± 1.62,22.49 ± 0.93,0.03 ± 0.00,5.93 ± 0.98,0.03 ± 0.01,94.02 ± 0.99,60.61 ± 3.39,3683.31 ± 422.33,47.48 ± 2.57,0.16 ± 0.01,metrics_performance_by_range_RMSE_Linear_H4_me...
24,ENTIRE,82.65 ± 1.41,15.31 ± 1.10,0.04 ± 0.01,1.99 ± 0.55,0.00 ± 0.00,97.96 ± 0.56,30.91 ± 1.24,956.44 ± 77.16,22.97 ± 0.95,0.13 ± 0.01,metrics_performance_by_range_RMSE_LSTM_H2_metr...
25,TBR_2,17.50 ± 18.85,0.00 ± 0.00,0.00 ± 0.00,82.38 ± 18.77,0.12 ± 0.13,17.50 ± 18.85,41.11 ± 6.70,1726.32 ± 573.50,37.52 ± 6.57,0.83 ± 0.14,metrics_performance_by_range_RMSE_LSTM_H2_metr...
26,TBR_1,17.72 ± 13.88,0.00 ± 0.00,0.00 ± 0.00,82.06 ± 13.75,0.23 ± 0.16,17.72 ± 13.88,28.56 ± 3.62,826.02 ± 209.33,24.26 ± 3.52,0.39 ± 0.06,metrics_performance_by_range_RMSE_LSTM_H2_metr...
27,TIR,83.89 ± 1.07,16.05 ± 1.07,0.07 ± 0.01,0.00 ± 0.00,0.00 ± 0.00,99.94 ± 0.01,20.81 ± 0.98,433.87 ± 40.78,15.09 ± 0.89,0.12 ± 0.00,metrics_performance_by_range_RMSE_LSTM_H2_metr...
28,TAR_1,84.13 ± 1.44,15.09 ± 1.38,0.03 ± 0.02,0.73 ± 0.09,0.00 ± 0.01,99.23 ± 0.10,32.31 ± 0.98,1044.52 ± 62.87,25.63 ± 0.79,0.12 ± 0.00,metrics_performance_by_range_RMSE_LSTM_H2_metr...
29,TAR_2,83.18 ± 1.29,15.07 ± 1.18,0.00 ± 0.00,1.75 ± 0.29,0.00 ± 0.00,98.25 ± 0.29,47.53 ± 1.99,2262.23 ± 191.75,40.29 ± 1.79,0.13 ± 0.00,metrics_performance_by_range_RMSE_LSTM_H2_metr...
30,ENTIRE,65.06 ± 2.19,30.52 ± 1.44,0.37 ± 0.13,4.01 ± 0.80,0.05 ± 0.02,95.57 ± 0.86,45.00 ± 2.12,2028.89 ± 192.18,33.18 ± 1.62,0.19 ± 0.01,metrics_performance_by_range_RMSE_LSTM_H4_metr...
31,TBR_2,0.00 ± 0.00,0.00 ± 0.00,0.00 ± 0.00,96.87 ± 1.81,3.13 ± 1.81,0.00 ± 0.00,74.31 ± 7.00,5560.73 ± 1056.65,70.34 ± 5.68,1.55 ± 0.11,metrics_performance_by_range_RMSE_LSTM_H4_metr...
32,TBR_1,0.05 ± 0.10,0.00 ± 0.00,0.00 ± 0.00,97.22 ± 1.38,2.73 ± 1.30,0.05 ± 0.10,58.83 ± 4.07,3473.67 ± 484.69,54.18 ± 2.65,0.87 ± 0.04,metrics_performance_by_range_RMSE_LSTM_H4_metr...
33,TIR,66.78 ± 2.13,32.58 ± 2.13,0.64 ± 0.22,0.00 ± 0.00,0.00 ± 0.00,99.36 ± 0.22,30.48 ± 1.23,930.20 ± 74.11,22.43 ± 0.79,0.19 ± 0.01,metrics_performance_by_range_RMSE_LSTM_H4_metr...
34,TAR_1,70.45 ± 1.19,27.28 ± 1.03,0.14 ± 0.10,2.14 ± 0.14,0.00 ± 0.00,97.72 ± 0.20,42.69 ± 1.10,1823.22 ± 93.64,33.38 ± 0.80,0.16 ± 0.00,metrics_performance_by_range_RMSE_LSTM_H4_metr...
35,TAR_2,58.18 ± 1.48,32.85 ± 2.11,0.00 ± 0.00,8.98 ± 1.19,0.00 ± 0.00,91.02 ± 1.19,72.09 ± 2.98,5204.29 ± 437.32,60.29 ± 2.59,0.20 ± 0.00,metrics_performance_by_range_RMSE_LSTM_H4_metr...

In [3]:
df_results['Algorithm'] = df_results['file_name'].apply(lambda x: x.split('_')[-6])
df_results['PH'] = df_results['file_name'].apply(lambda x: x.split('_')[-5][1:])
df_results['PH'] = df_results['PH'].astype(int)
df_all_results = df_results.sort_values(by=['Algorithm', 'PH'])
df_results = df_results.drop(columns=['file_name'])
df_results = df_results[['Algorithm', 'PH', 'Range', 'A', 'B', 'C', 'D', 'E', 'A + B', 'RMSE', 'MSE', 'MAE', 'MAPE']]
df_results

,Algorithm,PH,Range,A,B,C,D,E,A + B,RMSE,MSE,MAE,MAPE
0,CNN,2,ENTIRE,73.00 ± 1.45,23.98 ± 0.87,0.40 ± 0.12,2.60 ± 0.71,0.02 ± 0.01,96.98 ± 0.76,35.69 ± 1.34,1275.03 ± 95.63,25.95 ± 1.01,0.16 ± 0.01
1,CNN,2,TBR_2,3.08 ± 2.79,0.00 ± 0.00,0.00 ± 0.00,95.60 ± 2.17,1.32 ± 0.65,3.08 ± 2.79,62.43 ± 7.03,3937.01 ± 894.28,57.68 ± 6.74,1.27 ± 0.14
2,CNN,2,TBR_1,1.21 ± 0.67,0.00 ± 0.00,0.00 ± 0.00,97.43 ± 0.30,1.37 ± 0.56,1.21 ± 0.67,48.91 ± 3.85,2403.88 ± 378.64,43.55 ± 3.01,0.70 ± 0.05
3,CNN,2,TIR,67.97 ± 1.82,31.47 ± 1.80,0.56 ± 0.19,0.00 ± 0.00,0.00 ± 0.00,99.44 ± 0.19,29.76 ± 1.14,886.49 ± 68.13,21.84 ± 0.82,0.18 ± 0.01
4,CNN,2,TAR_1,80.66 ± 1.49,18.07 ± 1.40,0.34 ± 0.14,0.93 ± 0.15,0.00 ± 0.00,98.73 ± 0.21,35.17 ± 1.40,1238.15 ± 98.19,25.63 ± 1.18,0.12 ± 0.01
5,CNN,2,TAR_2,81.98 ± 2.54,14.82 ± 1.78,0.06 ± 0.02,3.14 ± 0.80,0.00 ± 0.00,96.80 ± 0.79,47.65 ± 3.62,2281.17 ± 352.20,35.94 ± 2.78,0.12 ± 0.01
6,CNN,4,ENTIRE,58.73 ± 2.45,36.03 ± 1.62,1.01 ± 0.23,4.11 ± 0.85,0.12 ± 0.05,94.76 ± 0.94,49.06 ± 2.48,2412.23 ± 245.33,36.86 ± 1.99,0.23 ± 0.02
7,CNN,4,TBR_2,0.00 ± 0.00,0.00 ± 0.00,0.00 ± 0.00,91.26 ± 5.39,8.74 ± 5.39,0.00 ± 0.00,92.86 ± 11.78,8733.36 ± 2241.12,87.64 ± 10.52,1.93 ± 0.22
8,CNN,4,TBR_1,0.01 ± 0.02,0.00 ± 0.00,0.00 ± 0.00,92.95 ± 2.92,7.03 ± 2.93,0.01 ± 0.02,76.19 ± 6.57,5839.78 ± 1022.68,70.59 ± 5.39,1.13 ± 0.08
9,CNN,4,TIR,53.49 ± 2.48,44.79 ± 2.45,1.72 ± 0.39,0.00 ± 0.00,0.00 ± 0.00,98.28 ± 0.39,40.15 ± 1.61,1613.74 ± 130.22,30.48 ± 1.10,0.26 ± 0.01
10,CNN,4,TAR_1,70.67 ± 2.23,26.85 ± 2.00,0.44 ± 0.20,2.04 ± 0.22,0.00 ± 0.00,97.52 ± 0.34,42.02 ± 1.95,1768.56 ± 164.20,32.27 ± 1.68,0.15 ± 0.01
11,CNN,4,TAR_2,60.30 ± 2.91,29.62 ± 1.43,0.01 ± 0.01,10.07 ± 1.91,0.00 ± 0.00,89.92 ± 1.90,72.34 ± 4.46,5249.20 ± 655.08,58.15 ± 3.73,0.19 ± 0.01
12,Linear,2,ENTIRE,83.50 ± 0.85,15.01 ± 0.73,0.13 ± 0.03,1.34 ± 0.36,0.02 ± 0.00,98.51 ± 0.38,26.72 ± 0.94,714.87 ± 49.61,19.15 ± 0.76,0.12 ± 0.00
13,Linear,2,TBR_2,55.78 ± 11.21,0.00 ± 0.00,0.00 ± 0.00,43.83 ± 10.84,0.39 ± 0.46,55.78 ± 11.21,33.65 ± 6.74,1168.90 ± 487.74,26.65 ± 5.02,0.59 ± 0.11
14,Linear,2,TBR_1,33.99 ± 2.52,0.00 ± 0.00,0.00 ± 0.00,65.74 ± 2.45,0.27 ± 0.10,33.99 ± 2.52,27.40 ± 2.87,757.45 ± 155.01,21.44 ± 1.83,0.34 ± 0.03
15,Linear,2,TIR,78.66 ± 1.37,21.18 ± 1.35,0.17 ± 0.05,0.00 ± 0.00,0.00 ± 0.00,99.83 ± 0.05,23.40 ± 1.10,548.61 ± 51.18,16.96 ± 0.84,0.14 ± 0.01
16,Linear,2,TAR_1,89.10 ± 0.92,10.36 ± 0.84,0.13 ± 0.05,0.36 ± 0.07,0.04 ± 0.01,99.46 ± 0.11,27.27 ± 1.13,744.67 ± 61.48,19.22 ± 0.89,0.09 ± 0.00
17,Linear,2,TAR_2,92.42 ± 1.03,6.67 ± 0.82,0.04 ± 0.01,0.87 ± 0.22,0.00 ± 0.00,99.09 ± 0.22,33.48 ± 2.02,1124.45 ± 139.98,24.86 ± 1.41,0.08 ± 0.00
18,Linear,4,ENTIRE,63.44 ± 2.02,32.57 ± 1.32,0.75 ± 0.18,3.13 ± 0.76,0.11 ± 0.03,96.02 ± 0.83,43.75 ± 1.96,1916.95 ± 171.74,32.63 ± 1.52,0.20 ± 0.01
19,Linear,4,TBR_2,7.92 ± 4.80,0.00 ± 0.00,0.00 ± 0.00,87.78 ± 4.27,4.30 ± 2.32,7.92 ± 4.80,68.29 ± 11.03,4760.84 ± 1531.71,59.32 ± 9.70,1.30 ± 0.20
20,Linear,4,TBR_1,4.45 ± 1.00,0.00 ± 0.00,0.00 ± 0.00,91.64 ± 1.77,3.91 ± 1.78,4.45 ± 1.00,58.29 ± 6.63,3433.19 ± 780.48,49.89 ± 5.41,0.80 ± 0.08
21,Linear,4,TIR,55.78 ± 1.89,43.01 ± 1.83,1.21 ± 0.30,0.00 ± 0.00,0.00 ± 0.00,98.79 ± 0.30,37.18 ± 1.56,1383.96 ± 115.32,28.27 ± 1.08,0.23 ± 0.01
22,Linear,4,TAR_1,75.47 ± 2.29,22.55 ± 2.07,0.44 ± 0.17,1.42 ± 0.18,0.11 ± 0.03,98.03 ± 0.30,40.35 ± 2.11,1632.06 ± 170.71,29.74 ± 1.78,0.14 ± 0.01
23,Linear,4,TAR_2,71.53 ± 1.62,22.49 ± 0.93,0.03 ± 0.00,5.93 ± 0.98,0.03 ± 0.01,94.02 ± 0.99,60.61 ± 3.39,3683.31 ± 422.33,47.48 ± 2.57,0.16 ± 0.01
24,LSTM,2,ENTIRE,82.65 ± 1.41,15.31 ± 1.10,0.04 ± 0.01,1.99 ± 0.55,0.00 ± 0.00,97.96 ± 0.56,30.91 ± 1.24,956.44 ± 77.16,22.97 ± 0.95,0.13 ± 0.01
25,LSTM,2,TBR_2,17.50 ± 18.85,0.00 ± 0.00,0.00 ± 0.00,82.38 ± 18.77,0.12 ± 0.13,17.50 ± 18.85,41.11 ± 6.70,1726.32 ± 573.50,37.52 ± 6.57,0.83 ± 0.14
26,LSTM,2,TBR_1,17.72 ± 13.88,0.00 ± 0.00,0.00 ± 0.00,82.06 ± 13.75,0.23 ± 0.16,17.72 ± 13.88,28.56 ± 3.62,826.02 ± 209.33,24.26 ± 3.52,0.39 ± 0.06
27,LSTM,2,TIR,83.89 ± 1.07,16.05 ± 1.07,0.07 ± 0.01,0.00 ± 0.00,0.00 ± 0.00,99.94 ± 0.01,20.81 ± 0.98,433.87 ± 40.78,15.09 ± 0.89,0.12 ± 0.00
28,LSTM,2,TAR_1,84.13 ± 1.44,15.09 ± 1.38,0.03 ± 0.02,0.73 ± 0.09,0.00 ± 0.01,99.23 ± 0.10,32.31 ± 0.98,1044.52 ± 62.87,25.63 ± 0.79,0.12 ± 0.00
29,LSTM,2,TAR_2,83.18 ± 1.29,15.07 ± 1.18,0.00 ± 0.00,1.75 ± 0.29,0.00 ± 0.00,98.25 ± 0.29,47.53 ± 1.99,2262.23 ± 191.75,40.29 ± 1.79,0.13 ± 0.00
30,LSTM,4,ENTIRE,65.06 ± 2.19,30.52 ± 1.44,0.37 ± 0.13,4.01 ± 0.80,0.05 ± 0.02,95.57 ± 0.86,45.00 ± 2.12,2028.89 ± 192.18,33.18 ± 1.62,0.19 ± 0.01
31,LSTM,4,TBR_2,0.00 ± 0.00,0.00 ± 0.00,0.00 ± 0.00,96.87 ± 1.81,3.13 ± 1.81,0.00 ± 0.00,74.31 ± 7.00,5560.73 ± 1056.65,70.34 ± 5.68,1.55 ± 0.11
32,LSTM,4,TBR_1,0.05 ± 0.10,0.00 ± 0.00,0.00 ± 0.00,97.22 ± 1.38,2.73 ± 1.30,0.05 ± 0.10,58.83 ± 4.07,3473.67 ± 484.69,54.18 ± 2.65,0.87 ± 0.04
33,LSTM,4,TIR,66.78 ± 2.13,32.58 ± 2.13,0.64 ± 0.22,0.00 ± 0.00,0.00 ± 0.00,99.36 ± 0.22,30.48 ± 1.23,930.20 ± 74.11,22.43 ± 0.79,0.19 ± 0.01
34,LSTM,4,TAR_1,70.45 ± 1.19,27.28 ± 1.03,0.14 ± 0.10,2.14 ± 0.14,0.00 ± 0.00,97.72 ± 0.20,42.69 ± 1.10,1823.22 ± 93.64,33.38 ± 0.80,0.16 ± 0.00
35,LSTM,4,TAR_2,58.18 ± 1.48,32.85 ± 2.11,0.00 ± 0.00,8.98 ± 1.19,0.00 ± 0.00,91.02 ± 1.19,72.09 ± 2.98,5204.29 ± 437.32,60.29 ± 2.59,0.20 ± 0.00

In [4]:
# df_results.to_excel('c:/Users/Ciro/Mi Unidad (PDI)/_UGR_PDI_2024-05-30/RELIEF-T1D/Python_projects/Glucose_prediction_2026/Experiments/Prediction_Bias_paper/T1DiabetesGranada/merged_performance_results_Replace-BG.xlsx', index=False)
df_results.to_excel('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Glucose_prediction_2026/Compare_Experiments/2026-01-23/2/Diatrend_fix_BGL_limit/merged_performance_results_Diatrend_FIX.xlsx', index=False)