Get the stats from the folds of the cross validation

In [1]:
import os
import pandas as pd
import numpy as np
from scipy.stats import t

In [12]:
def list_csv_files(directory):
    csv_files = [file for file in os.listdir(directory) if file.endswith('.csv')]
    return csv_files

directory_1 = 'c:/Users/Ciro/Mi Unidad (PDI)/_UGR_PDI_2024-05-30/RELIEF-T1D/Python_projects/CompareResults/DataPool/CrossValidation/Exp3/'
csv_files_1 = list_csv_files(directory_1)


def merge_csv_files(directory):
    csv_files = list_csv_files(directory)
    merged_df = pd.DataFrame()

    for file in csv_files:
        file_path = os.path.join(directory, file)
        df = pd.read_csv(file_path)
        df['file_name'] = file
        merged_df = pd.concat([merged_df, df], ignore_index=True)
    
    return merged_df



df_new_result_1 = merge_csv_files(directory_1)
df_new_result_1 = df_new_result_1.round(2)
df_new_result_1

,Range,A,B,C,D,E,A + B,RMSE,MSE,MAE,MAPE,file_name
0,ENTIRE,39.06,47.78,1.09,11.55,0.52,86.84,63.90,4083.09,49.79,0.38,metrics_performance_by_range_CNN_H12_Fold1.csv
1,TBR_2,0.00,0.00,0.00,91.73,8.27,0.00,100.89,10179.40,98.25,2.06,metrics_performance_by_range_CNN_H12_Fold1.csv
2,TBR_1,0.00,0.00,0.00,90.14,9.86,0.00,90.39,8170.21,87.16,1.42,metrics_performance_by_range_CNN_H12_Fold1.csv
3,TIR,44.09,53.58,1.79,0.49,0.06,97.67,45.66,2084.68,36.47,0.35,metrics_performance_by_range_CNN_H12_Fold1.csv
4,TAR_1,46.98,46.84,0.06,6.12,0.00,93.82,52.66,2773.38,45.13,0.21,metrics_performance_by_range_CNN_H12_Fold1.csv
...,...,...,...,...,...,...,...,...,...,...,...,...
535,TBR_2,0.00,0.00,0.00,96.10,3.90,0.00,74.57,5560.76,70.24,1.46,metrics_performance_by_range_LSTM_H8_Fold5.csv
536,TBR_1,0.00,0.00,0.00,95.19,4.81,0.00,67.38,4539.52,62.18,1.01,metrics_performance_by_range_LSTM_H8_Fold5.csv
537,TIR,53.33,45.09,1.08,0.48,0.03,98.42,37.28,1389.51,28.68,0.26,metrics_performance_by_range_LSTM_H8_Fold5.csv
538,TAR_1,55.45,39.93,0.16,4.46,0.00,95.38,53.16,2825.92,43.19,0.20,metrics_performance_by_range_LSTM_H8_Fold5.csv
539,TAR_2,26.91,47.47,0.00,25.62,0.00,74.38,106.30,11299.58,93.16,0.30,metrics_performance_by_range_LSTM_H8_Fold5.csv

In [13]:
df_new_result_1['Algorithm'] = df_new_result_1['file_name'].apply(lambda x: x.split('_')[-3])
df_new_result_1['PH'] = df_new_result_1['file_name'].apply(lambda x: x.split('_')[-2].split('.')[0][1:])
df_new_result_1['PH'] = df_new_result_1['PH'].astype(int)
df_new_result_1['Fold'] = df_new_result_1['file_name'].apply(lambda x: x.split('_')[-1].split('.')[0][-1])
df_new_result_1['Fold'] = df_new_result_1['Fold'].astype(int)
df_new_result_1

,Range,A,B,C,D,E,A + B,RMSE,MSE,MAE,MAPE,file_name,Algorithm,PH,Fold
0,ENTIRE,39.06,47.78,1.09,11.55,0.52,86.84,63.90,4083.09,49.79,0.38,metrics_performance_by_range_CNN_H12_Fold1.csv,CNN,12,1
1,TBR_2,0.00,0.00,0.00,91.73,8.27,0.00,100.89,10179.40,98.25,2.06,metrics_performance_by_range_CNN_H12_Fold1.csv,CNN,12,1
2,TBR_1,0.00,0.00,0.00,90.14,9.86,0.00,90.39,8170.21,87.16,1.42,metrics_performance_by_range_CNN_H12_Fold1.csv,CNN,12,1
3,TIR,44.09,53.58,1.79,0.49,0.06,97.67,45.66,2084.68,36.47,0.35,metrics_performance_by_range_CNN_H12_Fold1.csv,CNN,12,1
4,TAR_1,46.98,46.84,0.06,6.12,0.00,93.82,52.66,2773.38,45.13,0.21,metrics_performance_by_range_CNN_H12_Fold1.csv,CNN,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,TBR_2,0.00,0.00,0.00,96.10,3.90,0.00,74.57,5560.76,70.24,1.46,metrics_performance_by_range_LSTM_H8_Fold5.csv,LSTM,8,5
536,TBR_1,0.00,0.00,0.00,95.19,4.81,0.00,67.38,4539.52,62.18,1.01,metrics_performance_by_range_LSTM_H8_Fold5.csv,LSTM,8,5
537,TIR,53.33,45.09,1.08,0.48,0.03,98.42,37.28,1389.51,28.68,0.26,metrics_performance_by_range_LSTM_H8_Fold5.csv,LSTM,8,5
538,TAR_1,55.45,39.93,0.16,4.46,0.00,95.38,53.16,2825.92,43.19,0.20,metrics_performance_by_range_LSTM_H8_Fold5.csv,LSTM,8,5
539,TAR_2,26.91,47.47,0.00,25.62,0.00,74.38,106.30,11299.58,93.16,0.30,metrics_performance_by_range_LSTM_H8_Fold5.csv,LSTM,8,5

In [14]:
df_new_result_1 = df_new_result_1.drop(columns=['file_name'])
df_new_result_1

,Range,A,B,C,D,E,A + B,RMSE,MSE,MAE,MAPE,Algorithm,PH,Fold
0,ENTIRE,39.06,47.78,1.09,11.55,0.52,86.84,63.90,4083.09,49.79,0.38,CNN,12,1
1,TBR_2,0.00,0.00,0.00,91.73,8.27,0.00,100.89,10179.40,98.25,2.06,CNN,12,1
2,TBR_1,0.00,0.00,0.00,90.14,9.86,0.00,90.39,8170.21,87.16,1.42,CNN,12,1
3,TIR,44.09,53.58,1.79,0.49,0.06,97.67,45.66,2084.68,36.47,0.35,CNN,12,1
4,TAR_1,46.98,46.84,0.06,6.12,0.00,93.82,52.66,2773.38,45.13,0.21,CNN,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,TBR_2,0.00,0.00,0.00,96.10,3.90,0.00,74.57,5560.76,70.24,1.46,LSTM,8,5
536,TBR_1,0.00,0.00,0.00,95.19,4.81,0.00,67.38,4539.52,62.18,1.01,LSTM,8,5
537,TIR,53.33,45.09,1.08,0.48,0.03,98.42,37.28,1389.51,28.68,0.26,LSTM,8,5
538,TAR_1,55.45,39.93,0.16,4.46,0.00,95.38,53.16,2825.92,43.19,0.20,LSTM,8,5
539,TAR_2,26.91,47.47,0.00,25.62,0.00,74.38,106.30,11299.58,93.16,0.30,LSTM,8,5

In [15]:
desired_order = ["ENTIRE", "TBR_2", "TBR_1", "TIR", "TAR_1", "TAR_2"]

df_new_result_1["Range"] = pd.Categorical(df_new_result_1["Range"], categories=desired_order, ordered=True)
df_new_result_1

,Range,A,B,C,D,E,A + B,RMSE,MSE,MAE,MAPE,Algorithm,PH,Fold
0,ENTIRE,39.06,47.78,1.09,11.55,0.52,86.84,63.90,4083.09,49.79,0.38,CNN,12,1
1,TBR_2,0.00,0.00,0.00,91.73,8.27,0.00,100.89,10179.40,98.25,2.06,CNN,12,1
2,TBR_1,0.00,0.00,0.00,90.14,9.86,0.00,90.39,8170.21,87.16,1.42,CNN,12,1
3,TIR,44.09,53.58,1.79,0.49,0.06,97.67,45.66,2084.68,36.47,0.35,CNN,12,1
4,TAR_1,46.98,46.84,0.06,6.12,0.00,93.82,52.66,2773.38,45.13,0.21,CNN,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,TBR_2,0.00,0.00,0.00,96.10,3.90,0.00,74.57,5560.76,70.24,1.46,LSTM,8,5
536,TBR_1,0.00,0.00,0.00,95.19,4.81,0.00,67.38,4539.52,62.18,1.01,LSTM,8,5
537,TIR,53.33,45.09,1.08,0.48,0.03,98.42,37.28,1389.51,28.68,0.26,LSTM,8,5
538,TAR_1,55.45,39.93,0.16,4.46,0.00,95.38,53.16,2825.92,43.19,0.20,LSTM,8,5
539,TAR_2,26.91,47.47,0.00,25.62,0.00,74.38,106.30,11299.58,93.16,0.30,LSTM,8,5

In [16]:
df_new_result_1.to_excel('2025-06-05 - Exp3_full_result_table.xlsx', index=False)

In [17]:
def summarize_metrics(df: pd.DataFrame, group_cols: list, metric_cols: list) -> pd.DataFrame:
    """
    Compute summary statistics for metrics over cross-validation folds.

    Parameters
    ----------
    df : pd.DataFrame
        Your full result table (must include columns like 'Fold', 'RMSE', etc.).
    group_cols : list
        Columns to group by (e.g. ['Algorithm', 'PH', 'Range']).
    metric_cols : list
        Metrics to summarize (e.g. ['RMSE', 'MAE', 'MAPE']).

    Returns
    -------
    pd.DataFrame
        One row per group with full summary stats: mean, std, IC95%, median, IQR, CV.
    """
    results = []

    for keys, group in df.groupby(group_cols, observed=True):
        row = dict(zip(group_cols, keys)) if isinstance(keys, tuple) else {group_cols[0]: keys}
        n = len(group)

        for metric in metric_cols:
            values = group[metric].dropna()
            mean = values.mean()
            std = values.std(ddof=1)
            median = values.median()
            min = values.min()
            max = values.max()
            q1 = values.quantile(0.25)
            q3 = values.quantile(0.75)
            iqr = q3 - q1
            cv = std / mean if mean != 0 else np.nan

            # 95% confidence interval
            t_val = t.ppf(0.975, df=n-1) if n > 1 else np.nan
            margin = t_val * std / np.sqrt(n) if n > 1 else np.nan
            ic_lower = mean - margin if n > 1 else np.nan
            ic_upper = mean + margin if n > 1 else np.nan

            row.update({
                f"{metric}_mean": mean,
                f"{metric}_std": std,
                f"{metric}_cv": cv,
                f"{metric}_median": median,
                f"{metric}_min": min,
                f"{metric}_iq_25": q1,
                f"{metric}_iq_75": q3,
                f"{metric}_max": max,
                f"{metric}_iqr": iqr,
                f"{metric}_ci95_lower": ic_lower,
                f"{metric}_ci95_upper": ic_upper,
            })

        results.append(row)

    return pd.DataFrame(results)

In [18]:
group_cols = ['Algorithm', 'PH', 'Range']
metric_cols = ['A + B', 'RMSE']
df_summary_1 = summarize_metrics(df_new_result_1, group_cols, metric_cols)
df_summary_1 = df_summary_1.round(2)
df_summary_1

,Algorithm,PH,Range,A + B_mean,A + B_std,A + B_cv,A + B_median,A + B_min,A + B_iq_25,A + B_iq_75,...,RMSE_std,RMSE_cv,RMSE_median,RMSE_min,RMSE_iq_25,RMSE_iq_75,RMSE_max,RMSE_iqr,RMSE_ci95_lower,RMSE_ci95_upper
0,CNN,2,ENTIRE,95.71,0.34,0.00,95.60,95.38,95.56,95.72,...,0.33,0.01,28.56,28.38,28.43,28.64,29.20,0.21,28.23,29.05
1,CNN,2,TBR_2,38.82,3.26,0.08,37.96,35.23,36.44,41.98,...,1.76,0.06,30.92,29.17,29.63,30.92,33.70,1.29,28.68,33.06
2,CNN,2,TBR_1,21.39,0.93,0.04,21.62,20.41,20.53,21.71,...,1.43,0.05,28.97,28.05,28.40,29.39,31.68,0.99,27.53,31.07
3,CNN,2,TIR,99.48,0.03,0.00,99.48,99.45,99.46,99.49,...,0.20,0.01,24.63,24.35,24.53,24.73,24.89,0.20,24.37,24.88
4,CNN,2,TAR_1,99.18,0.06,0.00,99.21,99.07,99.20,99.21,...,0.63,0.02,31.38,30.95,31.20,31.53,32.58,0.33,30.75,32.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,Linear,16,TBR_2,0.00,0.00,2.24,0.00,0.00,0.00,0.00,...,2.11,0.02,103.52,103.07,103.11,103.75,108.03,0.64,101.68,106.91
104,Linear,16,TBR_1,0.00,0.00,NaN,0.00,0.00,0.00,0.00,...,1.79,0.02,92.95,91.80,92.63,93.02,96.46,0.39,91.15,95.60
105,Linear,16,TIR,98.21,0.28,0.00,98.31,97.72,98.28,98.36,...,1.12,0.02,45.87,45.38,45.42,46.29,48.11,0.87,44.82,47.61
106,Linear,16,TAR_1,93.10,0.18,0.00,93.02,92.93,92.96,93.28,...,0.70,0.01,52.47,51.96,52.23,53.02,53.71,0.79,51.81,53.54
107,Linear,16,TAR_2,45.30,1.23,0.03,45.68,44.00,44.02,46.08,...,4.06,0.03,131.24,126.29,130.52,134.40,137.00,3.88,126.84,136.94

In [19]:
df_summary_1.to_excel('2025-06-04 - Exp3_summary_stats.xlsx', index=False)

In [20]:
std_columns = [col for col in df_summary_1.columns if col.endswith('_std')]
df_summary_1[group_cols + std_columns]

    Algorithm  PH   Range  A + B_std  RMSE_std
0         CNN   2  ENTIRE       0.34      0.33
1         CNN   2   TBR_2       3.26      1.76
2         CNN   2   TBR_1       0.93      1.43
3         CNN   2     TIR       0.03      0.20
4         CNN   2   TAR_1       0.06      0.63
..        ...  ..     ...        ...       ...
103    Linear  16   TBR_2       0.00      2.11
104    Linear  16   TBR_1       0.00      1.79
105    Linear  16     TIR       0.28      1.12
106    Linear  16   TAR_1       0.18      0.70
107    Linear  16   TAR_2       1.23      4.06

[108 rows x 5 columns]

In [21]:
grouped = df_new_result_1.groupby(["Algorithm", "PH", "Range"])

# Calcular estadísticos clave
summary = grouped.agg({
    "A + B": ["mean", "std"],
    "RMSE":  ["mean", "std", "min", "max"]
})
summary

C:\Users\Ciro\AppData\Local\Temp\ipykernel_12452\861854599.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df_new_result_1.groupby(["Algorithm", "PH", "Range"])

                      A + B               RMSE
                       mean       std     mean       std     min     max
Algorithm PH Range
CNN       2  ENTIRE  95.706  0.338053   28.642  0.328512   28.38   29.20
             TBR_2   38.816  3.263438   30.868  1.763624   29.17   33.70
             TBR_1   21.386  0.931144   29.298  1.427750   28.05   31.68
             TIR     99.482  0.031145   24.626  0.203666   24.35   24.89
             TAR_1   99.184  0.064653   31.528  0.626554   30.95   32.58
...                     ...       ...      ...       ...     ...     ...
Linear    16 TBR_2    0.002  0.004472  104.296  2.106699  103.07  108.03
             TBR_1    0.000  0.000000   93.372  1.793006   91.80   96.46
             TIR     98.208  0.275264   46.214  1.123045   45.38   48.11
             TAR_1   93.100  0.181246   52.678  0.696685   51.96   53.71
             TAR_2   45.300  1.234666  131.890  4.064222  126.29  137.00

[108 rows x 6 columns]