In [1]:
import pandas as pd

In [2]:
df_bgl_gra = pd.read_parquet('c:/Users/Ciro/Mi Unidad (PDI)/_UGR_PDI_2024-05-30/RELIEF-T1D/Datasets/Preprocess/Glucose_measurements_T1DiabetesGranada.parquet')
print(df_bgl_gra.head())

  Patient_ID Measurement_date Measurement_time  Measurement  \
0  LIB193263       2020-06-09         19:08:00         99.0
1  LIB193263       2020-06-09         19:23:00         92.0
2  LIB193263       2020-06-09         19:38:00         86.0
3  LIB193263       2020-06-09         19:53:00         85.0
4  LIB193263       2020-06-09         20:08:00         85.0

                15min 5min
0 2020-06-09 19:15:00  NaT
1 2020-06-09 19:30:00  NaT
2 2020-06-09 19:45:00  NaT
3 2020-06-09 20:00:00  NaT
4 2020-06-09 20:15:00  NaT

In [3]:
df_bgl_gra['Patient_ID'].unique()

array(['LIB193263', 'LIB193264', 'LIB193265', 'LIB193266', 'LIB193267',
       'LIB193268', 'LIB193269', 'LIB193273', 'LIB193274', 'LIB193277',
       'LIB193279', 'LIB193280', 'LIB193281', 'LIB193284', 'LIB193302',
       'LIB193303', 'LIB193304', 'LIB193307', 'LIB193308', 'LIB193309',
       'LIB193310', 'LIB193311', 'LIB193312', 'LIB193313', 'LIB193314',
       'LIB193315', 'LIB193317', 'LIB193318', 'LIB193320', 'LIB193324',
       'LIB193325', 'LIB193330', 'LIB193332', 'LIB193333', 'LIB193334',
       'LIB193335', 'LIB193337', 'LIB193338', 'LIB193340', 'LIB193341',
       'LIB193342', 'LIB193344', 'LIB193345', 'LIB193346', 'LIB193347',
       'LIB193349', 'LIB193350', 'LIB193351', 'LIB193353', 'LIB193354',
       'LIB193356', 'LIB193357', 'LIB193358', 'LIB193361', 'LIB193363',
       'LIB193367', 'LIB193368', 'LIB193370', 'LIB193371', 'LIB193372',
       'LIB193375', 'LIB193376', 'LIB193378', 'LIB193379', 'LIB193380',
       'LIB193382', 'LIB193383', 'LIB193384', 'LIB193385', 'LIB193386',
       'LIB193389', 'LIB193391', 'LIB193392', 'LIB193393', 'LIB193395',
       'LIB193397', 'LIB193399', 'LIB193400', 'LIB193404', 'LIB193406',
       'LIB193407', 'LIB193408', 'LIB193410', 'LIB193411', 'LIB193412',
       'LIB193416', 'LIB193418', 'LIB193419', 'LIB193420', 'LIB193423',
       'LIB193424', 'LIB193425', 'LIB193427', 'LIB193428', 'LIB193430',
       'LIB193432', 'LIB193433', 'LIB193434', 'LIB193435', 'LIB193438',
       'LIB193440', 'LIB193441', 'LIB193442', 'LIB193444', 'LIB193445',
       'LIB193447', 'LIB193448', 'LIB193449', 'LIB193451', 'LIB193452',
       'LIB193454', 'LIB193455', 'LIB193457', 'LIB193458', 'LIB193459',
       'LIB193460', 'LIB193461', 'LIB193462', 'LIB193464', 'LIB193465',
       'LIB193466', 'LIB193467', 'LIB193469', 'LIB193470', 'LIB193471',
       'LIB193473', 'LIB193474', 'LIB193475', 'LIB193476', 'LIB193479',
       'LIB193480', 'LIB193481', 'LIB193482', 'LIB193483', 'LIB193484',
       'LIB193485', 'LIB193486', 'LIB193487', 'LIB193488', 'LIB193489',
       'LIB193490', 'LIB193493', 'LIB193494', 'LIB193495', 'LIB193497',
       'LIB193498', 'LIB193499', 'LIB193500', 'LIB193501', 'LIB193502',
       'LIB193503', 'LIB193504', 'LIB193505', 'LIB193506', 'LIB193507',
       'LIB193509', 'LIB193511', 'LIB193512', 'LIB193513', 'LIB193515',
       'LIB193518', 'LIB193520', 'LIB193521', 'LIB193522', 'LIB193523',
       'LIB193524', 'LIB193526', 'LIB193527', 'LIB193529', 'LIB193530',
       'LIB193531', 'LIB193532', 'LIB193534', 'LIB193535', 'LIB193536',
       'LIB193539', 'LIB193540', 'LIB193541', 'LIB193542', 'LIB193544',
       'LIB193545', 'LIB193546', 'LIB193549', 'LIB193550', 'LIB193551',
       'LIB193552', 'LIB193553', 'LIB193554', 'LIB193555', 'LIB193556',
       'LIB193557', 'LIB193558', 'LIB193559', 'LIB193561', 'LIB193562',
       'LIB193563', 'LIB193566', 'LIB193567', 'LIB193569', 'LIB193571',
       'LIB193572', 'LIB193573', 'LIB193574', 'LIB193575', 'LIB193576',
       'LIB193577', 'LIB193578', 'LIB193579', 'LIB193580', 'LIB193582',
       'LIB193584', 'LIB193585', 'LIB193586', 'LIB193587', 'LIB193588',
       'LIB193589', 'LIB193590', 'LIB193591', 'LIB193592', 'LIB193594',
       'LIB193595', 'LIB193596', 'LIB193598', 'LIB193599', 'LIB193600',
       'LIB193602', 'LIB193603', 'LIB193604', 'LIB193605', 'LIB193607',
       'LIB193608', 'LIB193610', 'LIB193611', 'LIB193613', 'LIB193614',
       'LIB193615', 'LIB193618', 'LIB193619', 'LIB193620', 'LIB193622',
       'LIB193623', 'LIB193625', 'LIB193626', 'LIB193628', 'LIB193630',
       'LIB193631', 'LIB193632', 'LIB193633', 'LIB193635', 'LIB193637',
       'LIB193638', 'LIB193639', 'LIB193644', 'LIB193645', 'LIB193646',
       'LIB193647', 'LIB193648', 'LIB193649', 'LIB193650', 'LIB193651',
       'LIB193652', 'LIB193653', 'LIB193655', 'LIB193656', 'LIB193657',
       'LIB193658', 'LIB193659', 'LIB193661', 'LIB193662', 'LIB193663',
       'LIB193664', 'LIB193666', 'LIB193668', 'LIB193669', 'LIB193670',
       'LIB193671', 'LIB193672', 'LIB193673', 'LIB193674', 'LIB193675',
       'LIB193677', 'LIB193678', 'LIB193680', 'LIB193681', 'LIB193682',
       'LIB193683', 'LIB193684', 'LIB193685', 'LIB193687', 'LIB193688',
       'LIB193689', 'LIB193690', 'LIB193691', 'LIB193692', 'LIB193694',
       'LIB193695', 'LIB193696', 'LIB193697', 'LIB193698', 'LIB193700',
       'LIB193701', 'LIB193704', 'LIB193705', 'LIB193706', 'LIB193707',
       'LIB193708', 'LIB193709', 'LIB193710', 'LIB193711', 'LIB193717',
       'LIB193720', 'LIB193721', 'LIB193722', 'LIB193723', 'LIB193724',
       'LIB193725', 'LIB193728', 'LIB193729', 'LIB193730', 'LIB193732',
       'LIB193733', 'LIB193734', 'LIB193736', 'LIB193737', 'LIB193739',
       'LIB193741', 'LIB193746', 'LIB193747', 'LIB193748', 'LIB193749',
       'LIB193750', 'LIB193751', 'LIB193753', 'LIB193755', 'LIB193757',
       'LIB193759', 'LIB193761', 'LIB193762', 'LIB193763', 'LIB193765',
       'LIB193769', 'LIB193770', 'LIB193771', 'LIB193772', 'LIB193773',
       'LIB193774', 'LIB193775', 'LIB193776', 'LIB193777', 'LIB193779',
       'LIB193782', 'LIB193783', 'LIB193785', 'LIB193786', 'LIB193787',
       'LIB193788', 'LIB193789', 'LIB193790', 'LIB193792', 'LIB193793',
       'LIB193795', 'LIB193796', 'LIB193798', 'LIB193799', 'LIB193800',
       'LIB193801', 'LIB193802', 'LIB193803', 'LIB193804', 'LIB193805',
       'LIB193806', 'LIB193809', 'LIB193810', 'LIB193812', 'LIB193813',
       'LIB193814', 'LIB193815', 'LIB193816', 'LIB193817', 'LIB193818',
       'LIB193819', 'LIB193820', 'LIB193821', 'LIB193822', 'LIB193824',
       'LIB193825', 'LIB193826', 'LIB193827', 'LIB193829', 'LIB193831',
       'LIB193832', 'LIB193833', 'LIB193835', 'LIB193836', 'LIB193837',
       'LIB193838', 'LIB193839', 'LIB193840', 'LIB193842', 'LIB193843',
       'LIB193844', 'LIB193846', 'LIB193847', 'LIB193848', 'LIB193849',
       'LIB193850', 'LIB193851', 'LIB193852', 'LIB193853', 'LIB193854',
       'LIB193856', 'LIB193857', 'LIB193858', 'LIB193859', 'LIB193861',
       'LIB193862', 'LIB193863', 'LIB193864', 'LIB193865', 'LIB193866',
       'LIB193867', 'LIB193868', 'LIB193869', 'LIB193870', 'LIB193871',
       'LIB193872', 'LIB193873', 'LIB193875', 'LIB193876', 'LIB193878',
       'LIB193880', 'LIB193881', 'LIB193882', 'LIB193884', 'LIB193886',
       'LIB193888', 'LIB193889', 'LIB193891', 'LIB193892', 'LIB193893',
       'LIB193894', 'LIB193895', 'LIB193896', 'LIB193897', 'LIB193898',
       'LIB193899', 'LIB193900', 'LIB193901', 'LIB193902', 'LIB193903',
       'LIB193906', 'LIB193907', 'LIB193910', 'LIB193913', 'LIB193914',
       'LIB193915', 'LIB193916', 'LIB193918', 'LIB193920', 'LIB193921',
       'LIB193922', 'LIB193923', 'LIB193924', 'LIB193925', 'LIB193926',
       'LIB193928', 'LIB193930', 'LIB193934', 'LIB193935', 'LIB193937',
       'LIB193938', 'LIB193939', 'LIB193940', 'LIB193941', 'LIB193942',
       'LIB193943', 'LIB193944', 'LIB193945', 'LIB193946', 'LIB193949',
       'LIB193950', 'LIB193951', 'LIB193956', 'LIB193957', 'LIB193959',
       'LIB193961', 'LIB193962', 'LIB193963', 'LIB193964', 'LIB193965',
       'LIB193967', 'LIB193968', 'LIB193969', 'LIB193971', 'LIB193973',
       'LIB193974', 'LIB193977', 'LIB193978', 'LIB193980', 'LIB193981',
       'LIB193982', 'LIB193983', 'LIB193984', 'LIB193985', 'LIB193987',
       'LIB193989', 'LIB193991', 'LIB193993', 'LIB193995', 'LIB193996',
       'LIB193997', 'LIB193998', 'LIB193999', 'LIB194002', 'LIB194003',
       'LIB194004', 'LIB194006', 'LIB194007', 'LIB194008', 'LIB194009',
       'LIB194010', 'LIB194011', 'LIB194012', 'LIB194013', 'LIB194014',
       'LIB194016', 'LIB194017', 'LIB194018', 'LIB194019', 'LIB194021',
       'LIB194022', 'LIB194025', 'LIB194026', 'LIB194027', 'LIB194028',
       'LIB194029', 'LIB194030', 'LIB194031', 'LIB194032', 'LIB194033',
       'LIB194035', 'LIB194036', 'LIB194037', 'LIB194039', 'LIB194040',
       'LIB194041', 'LIB194042', 'LIB194043', 'LIB194044', 'LIB194045',
       'LIB194046', 'LIB194047', 'LIB194050', 'LIB194051', 'LIB194052',
       'LIB194054', 'LIB194055', 'LIB194056', 'LIB194058', 'LIB194059',
       'LIB194061', 'LIB194062', 'LIB194063', 'LIB194066', 'LIB194067',
       'LIB194068', 'LIB194069', 'LIB194071', 'LIB194072', 'LIB194073',
       'LIB194074', 'LIB194076', 'LIB194077', 'LIB194079', 'LIB194080',
       'LIB194081', 'LIB194082', 'LIB194083', 'LIB194084', 'LIB194085',
       'LIB194086', 'LIB194087', 'LIB194089', 'LIB194090', 'LIB194092',
       'LIB194093', 'LIB194094', 'LIB194095', 'LIB194097', 'LIB194098',
       'LIB194099', 'LIB194101', 'LIB194102', 'LIB194104', 'LIB194105',
       'LIB194106', 'LIB194107', 'LIB194108', 'LIB194109', 'LIB194110',
       'LIB194111', 'LIB194112', 'LIB194113', 'LIB194114', 'LIB194115',
       'LIB194116', 'LIB194117', 'LIB194121', 'LIB194122', 'LIB194124',
       'LIB194125', 'LIB194126', 'LIB194127', 'LIB194128', 'LIB194129',
       'LIB194130', 'LIB194131', 'LIB194132', 'LIB194133', 'LIB194135',
       'LIB194136', 'LIB194137', 'LIB194140', 'LIB194141', 'LIB194142',
       'LIB194143', 'LIB194144', 'LIB194146', 'LIB194148', 'LIB194150',
       'LIB194153', 'LIB194155', 'LIB194156', 'LIB194157', 'LIB194158',
       'LIB194159', 'LIB194160', 'LIB194161', 'LIB194162', 'LIB194163',
       'LIB194164', 'LIB194165', 'LIB194166'], dtype=object)

In [12]:
pd.to_datetime(df_bgl_gra['Measurement_date']).iloc[:100].apply(lambda x: x.date())

0     2020-06-09
1     2020-06-09
2     2020-06-09
3     2020-06-09
4     2020-06-09
         ...
95    2020-06-10
96    2020-06-10
97    2020-06-10
98    2020-06-10
99    2020-06-10
Name: Measurement_date, Length: 100, dtype: object

In [4]:
df_bgl_replace = pd.read_parquet('c:/Users/Ciro/Mi Unidad (PDI)/_UGR_PDI_2024-05-30/RELIEF-T1D/Datasets/Preprocess/Glucose_measurements_DiaTrend.parquet', engine="pyarrow")
df_bgl_replace

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,1,2015-12-01,21:01:07,160.000000,2015-12-01 21:00:00,2015-12-01 21:00:00
1,1,2015-12-01,21:06:07,161.000000,NaT,2015-12-01 21:05:00
2,1,2015-12-01,21:11:08,165.000000,NaT,2015-12-01 21:10:00
3,1,2015-12-01,21:16:08,162.000000,2015-12-01 21:15:00,2015-12-01 21:15:00
4,1,2015-12-01,21:21:07,163.000000,NaT,2015-12-01 21:20:00
...,...,...,...,...,...,...
9165876,53,2019-09-27,15:17:58,153.866734,NaT,2019-09-27 15:20:00
9165877,53,2019-09-27,15:22:58,156.864138,NaT,2019-09-27 15:25:00
9165878,53,2019-09-27,15:27:58,156.864138,2019-09-27 15:30:00,2019-09-27 15:30:00
9165879,53,2019-09-27,15:32:58,156.864138,NaT,2019-09-27 15:35:00
9165880,53,2019-09-27,15:38:01,158.862408,NaT,2019-09-27 15:40:00

In [6]:
df_bgl_replace.to_csv('Glucose_measurements_DiaTrend.csv', index=False)

In [3]:
df_bgl_dia['Measurement_date'].iloc[0]

1448928000000000000

In [13]:
df_bgl_dia['Measurement_date'] = pd.to_datetime(df_bgl_dia['Measurement_date']).apply(lambda x: x.date())
df_bgl_dia

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,1,2015-12-01,0 days 21:01:07,160.000000,2015-12-01 21:00:00,2015-12-01 21:00:00
1,1,2015-12-01,0 days 21:06:07,161.000000,NaT,2015-12-01 21:05:00
2,1,2015-12-01,0 days 21:11:08,165.000000,NaT,2015-12-01 21:10:00
3,1,2015-12-01,0 days 21:16:08,162.000000,2015-12-01 21:15:00,2015-12-01 21:15:00
4,1,2015-12-01,0 days 21:21:07,163.000000,NaT,2015-12-01 21:20:00
...,...,...,...,...,...,...
9165876,53,2019-09-27,0 days 15:17:58,153.866734,NaT,2019-09-27 15:20:00
9165877,53,2019-09-27,0 days 15:22:58,156.864138,NaT,2019-09-27 15:25:00
9165878,53,2019-09-27,0 days 15:27:58,156.864138,2019-09-27 15:30:00,2019-09-27 15:30:00
9165879,53,2019-09-27,0 days 15:32:58,156.864138,NaT,2019-09-27 15:35:00
9165880,53,2019-09-27,0 days 15:38:01,158.862408,NaT,2019-09-27 15:40:00

In [10]:
pd.to_datetime(df_bgl_dia['Measurement_date']).iloc[:100].apply(lambda x: x.date())

0     2015-12-01
1     2015-12-01
2     2015-12-01
3     2015-12-01
4     2015-12-01
         ...
95           NaT
96           NaT
97           NaT
98           NaT
99           NaT
Name: Measurement_date, Length: 100, dtype: object

In [3]:
df_mios = df_bgl_dia[df_bgl_dia['15min'].notna()]
df_mios

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,LIB193263,1591660800000000000,0 days 19:08:00,99.0,2020-06-09 19:15:00,NaT
1,LIB193263,1591660800000000000,0 days 19:23:00,92.0,2020-06-09 19:30:00,NaT
2,LIB193263,1591660800000000000,0 days 19:38:00,86.0,2020-06-09 19:45:00,NaT
3,LIB193263,1591660800000000000,0 days 19:53:00,85.0,2020-06-09 20:00:00,NaT
4,LIB193263,1591660800000000000,0 days 20:08:00,85.0,2020-06-09 20:15:00,NaT
...,...,...,...,...,...,...
30477429,LIB194166,1647475200000000000,0 days 15:08:00,169.0,2022-03-17 15:15:00,NaT
30477430,LIB194166,1647475200000000000,0 days 15:23:00,206.0,2022-03-17 15:30:00,NaT
30477431,LIB194166,1647475200000000000,0 days 15:38:00,215.0,2022-03-17 15:45:00,NaT
30477432,LIB194166,1647475200000000000,0 days 15:53:00,204.0,2022-03-17 16:00:00,NaT
30477433,LIB194166,1647475200000000000,0 days 16:08:00,199.0,2022-03-17 16:15:00,NaT

In [4]:
df_mios.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30113515 entries, 0 to 30477433
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        object
 1   Measurement_date  object
 2   Measurement_time  timedelta64[us]
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(2), timedelta64[us](1)
memory usage: 1.6+ GB

In [10]:
df_mios['Measurement_time'].iloc[2]

Timedelta('0 days 19:38:00')

In [10]:
df_final = df_mios[['Patient_ID', 'Measurement', '15min']]
df_final

         Patient_ID  Measurement               15min
0         LIB193263         99.0 2020-06-09 19:15:00
1         LIB193263         92.0 2020-06-09 19:30:00
2         LIB193263         86.0 2020-06-09 19:45:00
3         LIB193263         85.0 2020-06-09 20:00:00
4         LIB193263         85.0 2020-06-09 20:15:00
...             ...          ...                 ...
30477429  LIB194166        169.0 2022-03-17 15:15:00
30477430  LIB194166        206.0 2022-03-17 15:30:00
30477431  LIB194166        215.0 2022-03-17 15:45:00
30477432  LIB194166        204.0 2022-03-17 16:00:00
30477433  LIB194166        199.0 2022-03-17 16:15:00

[30113515 rows x 3 columns]

In [11]:
df_final[df_final['Measurement'].isna()]

         Patient_ID  Measurement               15min
211       LIB193263          NaN 2020-06-11 23:45:00
500       LIB193263          NaN 2020-06-15 00:00:00
596       LIB193263          NaN 2020-06-15 23:45:00
756       LIB193263          NaN 2020-06-17 15:45:00
1272      LIB193263          NaN 2020-06-23 00:30:00
...             ...          ...                 ...
30477384  LIB194166          NaN 2022-03-17 04:00:00
30477385  LIB194166          NaN 2022-03-17 04:15:00
30477386  LIB194166          NaN 2022-03-17 04:30:00
30477387  LIB194166          NaN 2022-03-17 04:45:00
30477388  LIB194166          NaN 2022-03-17 05:00:00

[8244170 rows x 3 columns]

In [12]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30113515 entries, 0 to 30477433
Data columns (total 3 columns):
 #   Column       Dtype
---  ------       -----
 0   Patient_ID   object
 1   Measurement  float64
 2   15min        datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 919.0+ MB

In [13]:
df_final['date'] = df_final['15min'].dt.date
df_final

C:\Users\Ciro\AppData\Local\Temp\ipykernel_1496\4002329473.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['date'] = df_final['15min'].dt.date

         Patient_ID  Measurement               15min        date
0         LIB193263         99.0 2020-06-09 19:15:00  2020-06-09
1         LIB193263         92.0 2020-06-09 19:30:00  2020-06-09
2         LIB193263         86.0 2020-06-09 19:45:00  2020-06-09
3         LIB193263         85.0 2020-06-09 20:00:00  2020-06-09
4         LIB193263         85.0 2020-06-09 20:15:00  2020-06-09
...             ...          ...                 ...         ...
30477429  LIB194166        169.0 2022-03-17 15:15:00  2022-03-17
30477430  LIB194166        206.0 2022-03-17 15:30:00  2022-03-17
30477431  LIB194166        215.0 2022-03-17 15:45:00  2022-03-17
30477432  LIB194166        204.0 2022-03-17 16:00:00  2022-03-17
30477433  LIB194166        199.0 2022-03-17 16:15:00  2022-03-17

[30113515 rows x 4 columns]

In [8]:
df_no_mios = df_bgl_dia[df_bgl_dia['15min'].isna()]
df_no_mios

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
23,LIB193263,1591747200000000000,0 days 00:51:00,203.0,NaT,NaT
532,LIB193263,1592179200000000000,0 days 07:51:00,167.0,NaT,NaT
979,LIB193263,1592524800000000000,0 days 23:21:00,139.0,NaT,NaT
13182,LIB193263,1603584000000000000,0 days 02:02:00,197.0,NaT,NaT
13185,LIB193263,1603584000000000000,0 days 02:17:00,194.0,NaT,NaT
...,...,...,...,...,...,...
30475028,LIB194166,1645315200000000000,0 days 16:00:00,125.0,NaT,NaT
30475030,LIB194166,1645315200000000000,0 days 16:15:00,121.0,NaT,NaT
30475032,LIB194166,1645315200000000000,0 days 16:30:00,105.0,NaT,NaT
30475034,LIB194166,1645315200000000000,0 days 16:45:00,84.0,NaT,NaT
30475036,LIB194166,1645315200000000000,0 days 17:00:00,69.0,NaT,NaT

In [5]:
df_bgl_dia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30477434 entries, 0 to 30477433
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        object
 1   Measurement_date  object
 2   Measurement_time  timedelta64[us]
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(2), timedelta64[us](1)
memory usage: 1.4+ GB

In [8]:
df_bgl_dia

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,1,2015-12-01,0 days 21:01:07,160.00000,2015-12-01 21:00:00,2015-12-01 21:00:00
1,1,2015-12-01,0 days 21:06:07,161.00000,NaT,2015-12-01 21:05:00
2,1,2015-12-01,0 days 21:11:08,165.00000,NaT,2015-12-01 21:10:00
3,1,2015-12-01,0 days 21:16:08,162.00000,2015-12-01 21:15:00,2015-12-01 21:15:00
4,1,2015-12-01,0 days 21:21:07,163.00000,NaT,2015-12-01 21:20:00
...,...,...,...,...,...,...
9192454,54,2019-07-09,0 days 14:52:48,134.88318,NaT,2019-07-09 14:55:00
9192455,54,2019-07-09,0 days 14:57:48,132.88482,2019-07-09 15:00:00,2019-07-09 15:00:00
9192456,54,2019-07-09,0 days 15:02:48,131.88582,NaT,2019-07-09 15:05:00
9192457,54,2019-07-09,0 days 15:07:48,131.88582,NaT,2019-07-09 15:10:00
9192458,54,2019-07-09,0 days 15:12:48,131.88582,2019-07-09 15:15:00,2019-07-09 15:15:00

In [2]:
df_bgl = pd.read_csv('c:/Users/Ciro/Mi Unidad (Estudiante)/_UGR_in_go_2024-05-30/T1DiabetesGranada/T1DiabetesGranada/Glucose_measurements.csv')
df_bgl.head()

  Patient_ID Measurement_date Measurement_time  Measurement
0  LIB193263       2020-06-09         19:08:00           99
1  LIB193263       2020-06-09         19:23:00           92
2  LIB193263       2020-06-09         19:38:00           86
3  LIB193263       2020-06-09         19:53:00           85
4  LIB193263       2020-06-09         20:08:00           85

In [3]:
df_bgl

         Patient_ID Measurement_date Measurement_time  Measurement
0         LIB193263       2020-06-09         19:08:00           99
1         LIB193263       2020-06-09         19:23:00           92
2         LIB193263       2020-06-09         19:38:00           86
3         LIB193263       2020-06-09         19:53:00           85
4         LIB193263       2020-06-09         20:08:00           85
...             ...              ...              ...          ...
22671703  LIB194166       2022-03-17         15:08:00          169
22671704  LIB194166       2022-03-17         15:23:00          206
22671705  LIB194166       2022-03-17         15:38:00          215
22671706  LIB194166       2022-03-17         15:53:00          204
22671707  LIB194166       2022-03-17         16:08:00          199

[22671708 rows x 4 columns]

In [4]:
# TBR 2
df_tbr2 = df_bgl[df_bgl['Measurement'] < 54]
print(f'NUmber of measurements> {len(df_tbr2)}')
print(f'Percentage of measurements> {len(df_tbr2)/len(df_bgl)*100:.2f}%')

NUmber of measurements> 223505
Percentage of measurements> 0.99%

In [5]:
df_tbr1 = df_bgl[(df_bgl['Measurement'] >= 54) & (df_bgl['Measurement'] < 70)]
print(f'NUmber of measurements> {len(df_tbr1)}')
print(f'Percentage of measurements> {len(df_tbr1)/len(df_bgl)*100:.2f}%')

NUmber of measurements> 852915
Percentage of measurements> 3.76%

In [6]:
df_tir = df_bgl[(df_bgl['Measurement'] >= 70) & (df_bgl['Measurement'] < 181)]
print(f'NUmber of measurements> {len(df_tir)}')
print(f'Percentage of measurements> {len(df_tir)/len(df_bgl)*100:.2f}%')

NUmber of measurements> 13506999
Percentage of measurements> 59.58%

In [7]:
df_tar1 = df_bgl[(df_bgl['Measurement'] >= 181) & (df_bgl['Measurement'] < 251)]
print(f'NUmber of measurements> {len(df_tar1)}')
print(f'Percentage of measurements> {len(df_tar1)/len(df_bgl)*100:.2f}%')

NUmber of measurements> 5392360
Percentage of measurements> 23.78%

In [8]:
df_tar2 = df_bgl[df_bgl['Measurement'] >= 251]
print(f'NUmber of measurements> {len(df_tar2)}')
print(f'Percentage of measurements> {len(df_tar2)/len(df_bgl)*100:.2f}%')

NUmber of measurements> 2695929
Percentage of measurements> 11.89%