In [1]:
import pandas as pd

In [3]:
df_fold1 = pd.read_parquet(f'c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Eloy/Compare bad results/Compare folds/df_test_results_vectors_cSigP01_CNN_H2_Fold1.parquet')
df_fold2 = pd.read_parquet(f'c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Eloy/Compare bad results/Compare folds/df_test_results_vectors_cSigP01_CNN_H2_Fold2.parquet')
df_fold3 = pd.read_parquet(f'c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Eloy/Compare bad results/Compare folds/df_test_results_vectors_cSigP01_CNN_H2_Fold3.parquet')
df_fold4 = pd.read_parquet(f'c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Eloy/Compare bad results/Compare folds/df_test_results_vectors_cSigP01_CNN_H2_Fold4.parquet')
df_fold5 = pd.read_parquet(f'c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Eloy/Compare bad results/Compare folds/df_test_results_vectors_cSigP01_CNN_H2_Fold5.parquet')

In [4]:
df_concat = pd.concat([df_fold1, df_fold2, df_fold3, df_fold4, df_fold5], ignore_index=True)
df_concat

          y_test   y_predict
0            212  198.327988
1            195  188.806763
2            160  186.914658
3            124  193.161057
4            100  167.292084
...          ...         ...
19851235     245  326.773193
19851236     251  242.645660
19851237     287  201.374710
19851238     319  169.056015
19851239     333  276.143158

[19851240 rows x 2 columns]

In [6]:
df_all = pd.read_parquet(f'c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Eloy/Compare bad results/Compare folds/df_test_results_vectors_cSigP01_CNN_H2.parquet')
df_all

          y_test   y_predict
0            212  202.541245
1            195  206.051773
2            160  201.456131
3            124  164.787979
4            100  114.120834
...          ...         ...
59553715     245  326.773193
59553716     251  242.645660
59553717     287  201.374710
59553718     319  169.056015
59553719     333  276.143158

[59553720 rows x 2 columns]