In [1]:
import pandas as pd

In [2]:
df_old_windows_ph2 = pd.read_parquet('/home/cirorodriguezleon/RELIEF-T1D/datasets/After_2025-10-03/Preprocessed/diatrend/windows/few_fields/windows_with_folds_horizon_2.parquet')
df_old_windows_ph2

,x0,x1,x2,x3,x4,x5,x6,x7,y,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,160,162,167,150,164,147,130,137,143,1,val,train,test,val,train
1,162,167,150,164,147,130,137,131,135,1,val,train,test,val,train
2,167,150,164,147,130,137,131,143,143,1,val,train,test,val,train
3,177,176,195,194,153,117,100,94,74,1,val,train,test,val,train
4,176,195,194,153,117,100,94,83,81,1,val,train,test,val,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2322819,178,178,169,165,160,188,193,191,167,53,test,val,val,val,val
2322820,178,169,165,160,188,193,191,185,159,53,test,val,val,val,val
2322821,169,165,160,188,193,191,185,167,154,53,test,val,val,val,val
2322822,165,160,188,193,191,185,167,159,150,53,test,val,val,val,val
2322823,160,188,193,191,185,167,159,154,156,53,test,val,val,val,val

In [5]:
df_new_windows_ph2 = pd.read_parquet('/home/cirorodriguezleon/RELIEF-T1D/datasets/After_2025-10-03/Preprocessed/diatrend/windows/extra_fields/5folds/windows_with_5folds_DiaTrend_PH2.parquet')   
df_new_windows_ph2

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,160.0,162.0,167.0,150.0,164.0,147.0,130.0,137.0,143.0,2015-12-01,22:45:00,1,val,train,test,val,train
1,162.0,167.0,150.0,164.0,147.0,130.0,137.0,131.0,135.0,2015-12-01,23:00:00,1,val,train,test,val,train
2,167.0,150.0,164.0,147.0,130.0,137.0,131.0,143.0,143.0,2015-12-01,23:15:00,1,val,train,test,val,train
3,177.0,176.0,195.0,194.0,153.0,117.0,100.0,94.0,74.0,2015-12-04,20:45:00,1,val,train,test,val,train
4,176.0,195.0,194.0,153.0,117.0,100.0,94.0,83.0,81.0,2015-12-04,21:00:00,1,val,train,test,val,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2322819,178.8,178.8,169.9,165.9,160.9,188.8,193.8,191.8,167.9,2019-09-27,14:00:00,53,test,val,val,val,val
2322820,178.8,169.9,165.9,160.9,188.8,193.8,191.8,185.8,159.9,2019-09-27,14:15:00,53,test,val,val,val,val
2322821,169.9,165.9,160.9,188.8,193.8,191.8,185.8,167.9,154.9,2019-09-27,14:30:00,53,test,val,val,val,val
2322822,165.9,160.9,188.8,193.8,191.8,185.8,167.9,159.9,150.9,2019-09-27,14:45:00,53,test,val,val,val,val
2322823,160.9,188.8,193.8,191.8,185.8,167.9,159.9,154.9,156.9,2019-09-27,15:00:00,53,test,val,val,val,val

In [96]:
df_old_windows_ph4 = pd.read_parquet('/home/cirorodriguezleon/RELIEF-T1D/datasets/After_2025-10-03/Preprocessed/diatrend/windows/few_fields/windows_with_folds_horizon_4.parquet')
df_old_windows_ph4

,x0,x1,x2,x3,x4,x5,x6,x7,y,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,160,162,167,150,164,147,130,137,143,1,val,train,test,val,train
1,177,176,195,194,153,117,100,94,92,1,val,train,test,val,train
2,176,195,194,153,117,100,94,83,106,1,val,train,test,val,train
3,195,194,153,117,100,94,83,74,122,1,val,train,test,val,train
4,194,153,117,100,94,83,74,81,147,1,val,train,test,val,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2304684,207,190,178,178,169,165,160,188,167,53,test,val,val,val,val
2304685,190,178,178,169,165,160,188,193,159,53,test,val,val,val,val
2304686,178,178,169,165,160,188,193,191,154,53,test,val,val,val,val
2304687,178,169,165,160,188,193,191,185,150,53,test,val,val,val,val
2304688,169,165,160,188,193,191,185,167,156,53,test,val,val,val,val

In [110]:
df_new_windows_ph4 = pd.read_parquet('/home/cirorodriguezleon/RELIEF-T1D/datasets/After_2025-10-03/Preprocessed/diatrend/windows/extra_fields/5folds/windows_with_5folds_DiaTrend_PH4.parquet')
df_new_windows_ph4

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,160.0,162.0,167.0,150.0,164.0,147.0,130.0,137.0,143.0,2015-12-01,22:45:00,1,val,train,test,val,train
1,177.0,176.0,195.0,194.0,153.0,117.0,100.0,94.0,92.0,2015-12-04,20:45:00,1,val,train,test,val,train
2,176.0,195.0,194.0,153.0,117.0,100.0,94.0,83.0,106.0,2015-12-04,21:00:00,1,val,train,test,val,train
3,195.0,194.0,153.0,117.0,100.0,94.0,83.0,74.0,122.0,2015-12-04,21:15:00,1,val,train,test,val,train
4,194.0,153.0,117.0,100.0,94.0,83.0,74.0,81.0,147.0,2015-12-04,21:30:00,1,val,train,test,val,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2304684,207.8,190.8,178.8,178.8,169.9,165.9,160.9,188.8,167.9,2019-09-27,13:30:00,53,test,val,val,val,val
2304685,190.8,178.8,178.8,169.9,165.9,160.9,188.8,193.8,159.9,2019-09-27,13:45:00,53,test,val,val,val,val
2304686,178.8,178.8,169.9,165.9,160.9,188.8,193.8,191.8,154.9,2019-09-27,14:00:00,53,test,val,val,val,val
2304687,178.8,169.9,165.9,160.9,188.8,193.8,191.8,185.8,150.9,2019-09-27,14:15:00,53,test,val,val,val,val
2304688,169.9,165.9,160.9,188.8,193.8,191.8,185.8,167.9,156.9,2019-09-27,14:30:00,53,test,val,val,val,val

In [111]:
df_old_windows_ph4.iloc[2304556 - 10: 2304556 + 10]

          x0   x1   x2   x3   x4   x5   x6   x7    y  patient_id dataset
2304546  127  118  110  153  196  193  179  181  199          53     old
2304547  118  110  153  196  193  179  181  176  233          53     old
2304548  110  153  196  193  179  181  176  176  236          53     old
2304549  153  196  193  179  181  176  176  195  224          53     old
2304550  196  193  179  181  176  176  195  199  241          53     old
2304551  193  179  181  176  176  195  199  233  250          53     old
2304552  179  181  176  176  195  199  233  236  184          53     old
2304553  181  176  176  195  199  233  236  224  135          53     old
2304554  176  176  195  199  233  236  224  241   88          53     old
2304555  176  195  199  233  236  224  241  250   54          53     old
2304556  195  199  233  236  224  241  250  184   49          53     old
2304557  199  233  236  224  241  250  184  135   72          53     old
2304558  233  236  224  241  250  184  135   88   76          53     old
2304559  236  224  241  250  184  135   88   54   79          53     old
2304560  224  241  250  184  135   88   54   49   69          53     old
2304561  241  250  184  135   88   54   49   72   78          53     old
2304562  250  184  135   88   54   49   72   76   71          53     old
2304563  184  135   88   54   49   72   76   79   69          53     old
2304564  135   88   54   49   72   76   79   69   67          53     old
2304565   88   54   49   72   76   79   69   78   59          53     old

In [112]:
df_new_windows_ph4.iloc[2304556 - 10: 2304556 + 10]

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
2304546,127.9,118.9,110.9,153.9,196.8,193.8,179.8,181.8,199.8,2019-09-25,22:30:00,53,test,val,val,val,val
2304547,118.9,110.9,153.9,196.8,193.8,179.8,181.8,176.8,233.8,2019-09-25,22:45:00,53,test,val,val,val,val
2304548,110.9,153.9,196.8,193.8,179.8,181.8,176.8,176.8,236.8,2019-09-25,23:00:00,53,test,val,val,val,val
2304549,153.9,196.8,193.8,179.8,181.8,176.8,176.8,195.8,224.8,2019-09-25,23:15:00,53,test,val,val,val,val
2304550,196.8,193.8,179.8,181.8,176.8,176.8,195.8,199.8,241.8,2019-09-25,23:30:00,53,test,val,val,val,val
2304551,193.8,179.8,181.8,176.8,176.8,195.8,199.8,233.8,250.8,2019-09-25,23:45:00,53,test,val,val,val,val
2304552,179.8,181.8,176.8,176.8,195.8,199.8,233.8,236.8,184.8,2019-09-26,00:00:00,53,test,val,val,val,val
2304553,181.8,176.8,176.8,195.8,199.8,233.8,236.8,224.8,135.9,2019-09-26,00:15:00,53,test,val,val,val,val
2304554,176.8,176.8,195.8,199.8,233.8,236.8,224.8,241.8,88.9,2019-09-26,00:30:00,53,test,val,val,val,val
2304555,176.8,195.8,199.8,233.8,236.8,224.8,241.8,250.8,55.0,2019-09-26,00:45:00,53,test,val,val,val,val
2304556,195.8,199.8,233.8,236.8,224.8,241.8,250.8,184.8,50.0,2019-09-26,01:00:00,53,test,val,val,val,val
2304557,199.8,233.8,236.8,224.8,241.8,250.8,184.8,135.9,72.9,2019-09-26,01:15:00,53,test,val,val,val,val
2304558,233.8,236.8,224.8,241.8,250.8,184.8,135.9,88.9,76.9,2019-09-26,01:30:00,53,test,val,val,val,val
2304559,236.8,224.8,241.8,250.8,184.8,135.9,88.9,55.0,79.9,2019-09-26,01:45:00,53,test,val,val,val,val
2304560,224.8,241.8,250.8,184.8,135.9,88.9,55.0,50.0,69.9,2019-09-26,02:00:00,53,test,val,val,val,val
2304561,241.8,250.8,184.8,135.9,88.9,55.0,50.0,72.9,78.9,2019-09-26,02:15:00,53,test,val,val,val,val
2304562,250.8,184.8,135.9,88.9,55.0,50.0,72.9,76.9,71.9,2019-09-26,02:30:00,53,test,val,val,val,val
2304563,184.8,135.9,88.9,55.0,50.0,72.9,76.9,79.9,69.9,2019-09-26,02:45:00,53,test,val,val,val,val
2304564,135.9,88.9,55.0,50.0,72.9,76.9,79.9,69.9,67.9,2019-09-26,03:00:00,53,test,val,val,val,val
2304565,88.9,55.0,50.0,72.9,76.9,79.9,69.9,78.9,59.9,2019-09-26,03:15:00,53,test,val,val,val,val

In [113]:
# Truncate to int
number_columns = df_new_windows_ph2.select_dtypes(include=['float64', 'int64']).columns
df_ph2_new_int = df_new_windows_ph2[number_columns].astype(int)

In [114]:
# Convert to int  number columns
number_columns = df_new_windows_ph4.select_dtypes(include=['float64', 'int64']).columns
df_ph4_new_int = df_new_windows_ph4[number_columns].astype(int)
df_new_windows_ph4 = df_new_windows_ph4[number_columns].astype(int)
df_ph4_new_int

          x0   x1   x2   x3   x4   x5   x6   x7    y  patient_id
0        160  162  167  150  164  147  130  137  143           1
1        177  176  195  194  153  117  100   94   92           1
2        176  195  194  153  117  100   94   83  106           1
3        195  194  153  117  100   94   83   74  122           1
4        194  153  117  100   94   83   74   81  147           1
...      ...  ...  ...  ...  ...  ...  ...  ...  ...         ...
2304684  207  190  178  178  169  165  160  188  167          53
2304685  190  178  178  169  165  160  188  193  159          53
2304686  178  178  169  165  160  188  193  191  154          53
2304687  178  169  165  160  188  193  191  185  150          53
2304688  169  165  160  188  193  191  185  167  156          53

[2304689 rows x 10 columns]

In [115]:
df_ph4_new_int.duplicated().value_counts()

False    2304689
Name: count, dtype: int64

In [116]:
df_ph4_new_int.shape[0] - df_old_windows_ph4.shape[0]

0

In [117]:
df_old_windows_ph4  = df_old_windows_ph4[number_columns]
df_old_windows_ph4['dataset'] = 'old'
df_ph4_new_int['dataset'] = 'new'

In [118]:
df_ph4_new_int

          x0   x1   x2   x3   x4   x5   x6   x7    y  patient_id dataset
0        160  162  167  150  164  147  130  137  143           1     new
1        177  176  195  194  153  117  100   94   92           1     new
2        176  195  194  153  117  100   94   83  106           1     new
3        195  194  153  117  100   94   83   74  122           1     new
4        194  153  117  100   94   83   74   81  147           1     new
...      ...  ...  ...  ...  ...  ...  ...  ...  ...         ...     ...
2304684  207  190  178  178  169  165  160  188  167          53     new
2304685  190  178  178  169  165  160  188  193  159          53     new
2304686  178  178  169  165  160  188  193  191  154          53     new
2304687  178  169  165  160  188  193  191  185  150          53     new
2304688  169  165  160  188  193  191  185  167  156          53     new

[2304689 rows x 11 columns]

In [119]:
# Find the difference between the two dataframes
difference_ph4 = pd.concat([df_old_windows_ph4, df_ph4_new_int]).drop_duplicates(subset=['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'y', 'patient_id'], keep=False)
difference_ph4

          x0   x1   x2   x3   x4   x5   x6   x7   y  patient_id dataset
2117071  138  138  138  137  133  133  130  123  42          29     old
2117072  138  138  137  133  133  130  123  100  38          29     old
2117073  138  137  133  133  130  123  100   69  38          29     old
2117074  137  133  133  130  123  100   69   57  38          29     old
2117075  133  133  130  123  100   69   57   42  43          29     old
...      ...  ...  ...  ...  ...  ...  ...  ...  ..         ...     ...
2304563  184  135   88   55   50   72   76   79  69          53     new
2304564  135   88   55   50   72   76   79   69  67          53     new
2304565   88   55   50   72   76   79   69   78  59          53     new
2304566   55   50   72   76   79   69   78   71  72          53     new
2304567   50   72   76   79   69   78   71   69  85          53     new

[4284 rows x 11 columns]

In [120]:
difference_ph4[difference_ph4['dataset'] == 'old']

          x0   x1   x2   x3   x4   x5   x6   x7   y  patient_id dataset
2117071  138  138  138  137  133  133  130  123  42          29     old
2117072  138  138  137  133  133  130  123  100  38          29     old
2117073  138  137  133  133  130  123  100   69  38          29     old
2117074  137  133  133  130  123  100   69   57  38          29     old
2117075  133  133  130  123  100   69   57   42  43          29     old
...      ...  ...  ...  ...  ...  ...  ...  ...  ..         ...     ...
2304563  184  135   88   54   49   72   76   79  69          53     old
2304564  135   88   54   49   72   76   79   69  67          53     old
2304565   88   54   49   72   76   79   69   78  59          53     old
2304566   54   49   72   76   79   69   78   71  72          53     old
2304567   49   72   76   79   69   78   71   69  85          53     old

[2142 rows x 11 columns]

In [121]:
difference_ph4[difference_ph4['dataset'] == 'new']

          x0   x1   x2   x3   x4   x5   x6   x7   y  patient_id dataset
2117071  138  138  138  137  133  133  130  123  43          29     new
2117072  138  138  137  133  133  130  123  100  39          29     new
2117073  138  137  133  133  130  123  100   69  39          29     new
2117074  137  133  133  130  123  100   69   57  39          29     new
2117075  133  133  130  123  100   69   57   43  44          29     new
...      ...  ...  ...  ...  ...  ...  ...  ...  ..         ...     ...
2304563  184  135   88   55   50   72   76   79  69          53     new
2304564  135   88   55   50   72   76   79   69  67          53     new
2304565   88   55   50   72   76   79   69   78  59          53     new
2304566   55   50   72   76   79   69   78   71  72          53     new
2304567   50   72   76   79   69   78   71   69  85          53     new

[2142 rows x 11 columns]

In [109]:
difference_ph4['dataset'].value_counts()

Series([], Name: count, dtype: int64)

In [58]:
difference_ph4.loc[2304556]

          x0   x1   x2   x3   x4   x5   x6   x7   y  patient_id dataset
2304556  195  199  233  236  224  241  250  184  49          53     old
2304556  195  199  233  236  224  241  250  184  50          53     new

In [59]:
df_old_windows_ph4.loc[2304556]

x0            195
x1            199
x2            233
x3            236
x4            224
x5            241
x6            250
x7            184
y              49
patient_id     53
dataset       old
Name: 2304556, dtype: object

In [63]:
df_new_windows_ph4.loc[2304556]

x0                 195.8
x1                 199.8
x2                 233.8
x3                 236.8
x4                 224.8
x5                 241.8
x6                 250.8
x7                 184.8
y                   50.0
x_date_7      2019-09-26
x_time_7        01:00:00
patient_id            53
fold_0              test
fold_1               val
fold_2               val
fold_3               val
fold_4               val
Name: 2304556, dtype: object

Original window

In [70]:
df_original_window_ph4_new = pd.read_parquet('/home/cirorodriguezleon/RELIEF-T1D/datasets/After_2025-10-03/Preprocessed/diatrend/windows/extra_fields/windows_DiaTrend_PH4.parquet')
df_original_window_ph4_new.iloc[2304556 - 10: 2304556 + 10]

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id
2304546,127.9,118.9,110.9,153.9,196.8,193.8,179.8,181.8,199.8,2019-09-25,22:30:00,53
2304547,118.9,110.9,153.9,196.8,193.8,179.8,181.8,176.8,233.8,2019-09-25,22:45:00,53
2304548,110.9,153.9,196.8,193.8,179.8,181.8,176.8,176.8,236.8,2019-09-25,23:00:00,53
2304549,153.9,196.8,193.8,179.8,181.8,176.8,176.8,195.8,224.8,2019-09-25,23:15:00,53
2304550,196.8,193.8,179.8,181.8,176.8,176.8,195.8,199.8,241.8,2019-09-25,23:30:00,53
2304551,193.8,179.8,181.8,176.8,176.8,195.8,199.8,233.8,250.8,2019-09-25,23:45:00,53
2304552,179.8,181.8,176.8,176.8,195.8,199.8,233.8,236.8,184.8,2019-09-26,00:00:00,53
2304553,181.8,176.8,176.8,195.8,199.8,233.8,236.8,224.8,135.9,2019-09-26,00:15:00,53
2304554,176.8,176.8,195.8,199.8,233.8,236.8,224.8,241.8,88.9,2019-09-26,00:30:00,53
2304555,176.8,195.8,199.8,233.8,236.8,224.8,241.8,250.8,55.0,2019-09-26,00:45:00,53
2304556,195.8,199.8,233.8,236.8,224.8,241.8,250.8,184.8,50.0,2019-09-26,01:00:00,53
2304557,199.8,233.8,236.8,224.8,241.8,250.8,184.8,135.9,72.9,2019-09-26,01:15:00,53
2304558,233.8,236.8,224.8,241.8,250.8,184.8,135.9,88.9,76.9,2019-09-26,01:30:00,53
2304559,236.8,224.8,241.8,250.8,184.8,135.9,88.9,55.0,79.9,2019-09-26,01:45:00,53
2304560,224.8,241.8,250.8,184.8,135.9,88.9,55.0,50.0,69.9,2019-09-26,02:00:00,53
2304561,241.8,250.8,184.8,135.9,88.9,55.0,50.0,72.9,78.9,2019-09-26,02:15:00,53
2304562,250.8,184.8,135.9,88.9,55.0,50.0,72.9,76.9,71.9,2019-09-26,02:30:00,53
2304563,184.8,135.9,88.9,55.0,50.0,72.9,76.9,79.9,69.9,2019-09-26,02:45:00,53
2304564,135.9,88.9,55.0,50.0,72.9,76.9,79.9,69.9,67.9,2019-09-26,03:00:00,53
2304565,88.9,55.0,50.0,72.9,76.9,79.9,69.9,78.9,59.9,2019-09-26,03:15:00,53

original data

In [14]:
df_diatrend = pd.read_parquet('/home/cirorodriguezleon/RELIEF-T1D/datasets/After_2025-10-03/Preprocessed/t1diabetesgranada/Final versions V4/Filtered_for_prediction/Glucose_measurements_FILTERED_2025-11-21.parquet')
df_diatrend

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,LIB193263,2020-06-09,19:08:00,99.0,2020-06-09 19:15:00,NaT
1,LIB193263,2020-06-09,19:23:00,92.0,2020-06-09 19:30:00,NaT
2,LIB193263,2020-06-09,19:38:00,86.0,2020-06-09 19:45:00,NaT
3,LIB193263,2020-06-09,19:53:00,85.0,2020-06-09 20:00:00,NaT
4,LIB193263,2020-06-09,20:08:00,85.0,2020-06-09 20:15:00,NaT
...,...,...,...,...,...,...
30477429,LIB194166,None,None,NaN,2022-03-17 04:00:00,NaT
30477430,LIB194166,None,None,NaN,2022-03-17 04:15:00,NaT
30477431,LIB194166,None,None,NaN,2022-03-17 04:30:00,NaT
30477432,LIB194166,None,None,NaN,2022-03-17 04:45:00,NaT
30477433,LIB194166,None,None,NaN,2022-03-17 05:00:00,NaT

In [13]:
df_diatrend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11579408 entries, 0 to 11579407
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int32
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int32(1), object(2)
memory usage: 485.9+ MB

In [93]:

from datetime import date
exact_date = date(2019, 9, 20)

In [94]:
# Rows with the same date as exact_date
df_diatrend[df_diatrend['Measurement_date'] == exact_date]

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
243775,1,2019-09-20,00:00:14,124.000000,2019-09-20 00:00:00,2019-09-20 00:00:00
243776,1,2019-09-20,00:05:13,133.000000,NaT,2019-09-20 00:05:00
243777,1,2019-09-20,00:10:13,142.000000,NaT,2019-09-20 00:10:00
243778,1,2019-09-20,00:15:13,157.000000,2019-09-20 00:15:00,2019-09-20 00:15:00
243779,1,2019-09-20,00:20:13,168.000000,NaT,2019-09-20 00:20:00
...,...,...,...,...,...,...
9149601,53,2019-09-20,23:38:32,202.824332,NaT,2019-09-20 23:40:00
9149602,53,2019-09-20,23:43:32,183.840773,2019-09-20 23:45:00,2019-09-20 23:45:00
9149603,53,2019-09-20,23:48:32,164.857215,NaT,2019-09-20 23:50:00
9149604,53,2019-09-20,23:53:32,147.871926,NaT,2019-09-20 23:55:00
9149605,53,2019-09-20,23:58:32,130.886638,2019-09-21 00:00:00,2019-09-21 00:00:00

In [95]:
df_diatrend[(df_diatrend['Patient_ID'] == 53) & (df_diatrend['Measurement_date'] ==  exact_date)]

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
9149318,53,2019-09-20,00:03:37,298.741257,NaT,2019-09-20 00:05:00
9149319,53,2019-09-20,00:08:37,294.744718,NaT,2019-09-20 00:10:00
9149320,53,2019-09-20,00:13:37,280.756833,2019-09-20 00:15:00,2019-09-20 00:15:00
9149321,53,2019-09-20,00:18:39,279.757699,NaT,2019-09-20 00:20:00
9149322,53,2019-09-20,00:23:37,275.761160,NaT,2019-09-20 00:25:00
...,...,...,...,...,...,...
9149601,53,2019-09-20,23:38:32,202.824332,NaT,2019-09-20 23:40:00
9149602,53,2019-09-20,23:43:32,183.840773,2019-09-20 23:45:00,2019-09-20 23:45:00
9149603,53,2019-09-20,23:48:32,164.857215,NaT,2019-09-20 23:50:00
9149604,53,2019-09-20,23:53:32,147.871926,NaT,2019-09-20 23:55:00
9149605,53,2019-09-20,23:58:32,130.886638,2019-09-21 00:00:00,2019-09-21 00:00:00

In [91]:
df_diatrend['15min'].notna()

0           True
1          False
2          False
3           True
4          False
           ...
9155084    False
9155085    False
9155086     True
9155087    False
9155088    False
Name: 15min, Length: 9155089, dtype: bool

In [15]:
df = df_diatrend[(df_diatrend['15min'].notna()) & (df_diatrend['Measurement'] % 1 >= 0.001)]
df

Empty DataFrame
Columns: [Patient_ID, Measurement_date, Measurement_time, Measurement, 15min, 5min]
Index: []

In [9]:
df['Patient_ID'].value_counts()

Patient_ID
29    18307
31    16700
30    16347
37     9486
38     9267
36     9153
39     8769
42     7434
45     5127
46     4510
47     4114
49     3602
51     3076
53     2988
Name: count, dtype: int64

In [10]:
df.shape

(118880, 6)