In [1]:
import pandas as pd

In [5]:
df_old_windows_ph2 = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/diatrend/files_for_crossvalidation/windows/windows_horizon_2.parquet')
df_old_windows_ph2

          x0   x1   x2   x3   x4   x5   x6   x7    y  patient_id
0        160  162  167  150  164  147  130  137  143           1
1        162  167  150  164  147  130  137  131  135           1
2        167  150  164  147  130  137  131  143  143           1
3        177  176  195  194  153  117  100   94   74           1
4        176  195  194  153  117  100   94   83   81           1
...      ...  ...  ...  ...  ...  ...  ...  ...  ...         ...
2322819  178  178  169  165  160  188  193  191  167          53
2322820  178  169  165  160  188  193  191  185  159          53
2322821  169  165  160  188  193  191  185  167  154          53
2322822  165  160  188  193  191  185  167  159  150          53
2322823  160  188  193  191  185  167  159  154  156          53

[2322824 rows x 10 columns]

In [6]:
df_old_windows_ph4 = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/diatrend/files_for_crossvalidation/windows/windows_horizon_4.parquet')
df_old_windows_ph4

          x0   x1   x2   x3   x4   x5   x6   x7    y  patient_id
0        160  162  167  150  164  147  130  137  143           1
1        177  176  195  194  153  117  100   94   92           1
2        176  195  194  153  117  100   94   83  106           1
3        195  194  153  117  100   94   83   74  122           1
4        194  153  117  100   94   83   74   81  147           1
...      ...  ...  ...  ...  ...  ...  ...  ...  ...         ...
2304684  207  190  178  178  169  165  160  188  167          53
2304685  190  178  178  169  165  160  188  193  159          53
2304686  178  178  169  165  160  188  193  191  154          53
2304687  178  169  165  160  188  193  191  185  150          53
2304688  169  165  160  188  193  191  185  167  156          53

[2304689 rows x 10 columns]

In [4]:
df_new_windows_ph2 = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/windows/Extra_Fields/windows_horizon_DiaTrend_2.parquet')   
df_new_windows_ph2

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id
0,160.0,162.0,167.0,150.0,164.0,147.0,130.0,137.0,143.0,2015-12-01,22:45:00,1
1,162.0,167.0,150.0,164.0,147.0,130.0,137.0,131.0,135.0,2015-12-01,23:00:00,1
2,167.0,150.0,164.0,147.0,130.0,137.0,131.0,143.0,143.0,2015-12-01,23:15:00,1
3,177.0,176.0,195.0,194.0,153.0,117.0,100.0,94.0,74.0,2015-12-04,20:45:00,1
4,176.0,195.0,194.0,153.0,117.0,100.0,94.0,83.0,81.0,2015-12-04,21:00:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2322819,178.8,178.8,169.9,165.9,160.9,188.8,193.8,191.8,167.9,2019-09-27,14:00:00,53
2322820,178.8,169.9,165.9,160.9,188.8,193.8,191.8,185.8,159.9,2019-09-27,14:15:00,53
2322821,169.9,165.9,160.9,188.8,193.8,191.8,185.8,167.9,154.9,2019-09-27,14:30:00,53
2322822,165.9,160.9,188.8,193.8,191.8,185.8,167.9,159.9,150.9,2019-09-27,14:45:00,53
2322823,160.9,188.8,193.8,191.8,185.8,167.9,159.9,154.9,156.9,2019-09-27,15:00:00,53

In [7]:
df_new_windows_ph4 = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/windows/Extra_Fields/windows_horizon_DiaTrend_4.parquet')
df_new_windows_ph4

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id
0,160.0,162.0,167.0,150.0,164.0,147.0,130.0,137.0,143.0,2015-12-01,22:45:00,1
1,177.0,176.0,195.0,194.0,153.0,117.0,100.0,94.0,92.0,2015-12-04,20:45:00,1
2,176.0,195.0,194.0,153.0,117.0,100.0,94.0,83.0,106.0,2015-12-04,21:00:00,1
3,195.0,194.0,153.0,117.0,100.0,94.0,83.0,74.0,122.0,2015-12-04,21:15:00,1
4,194.0,153.0,117.0,100.0,94.0,83.0,74.0,81.0,147.0,2015-12-04,21:30:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2304684,207.8,190.8,178.8,178.8,169.9,165.9,160.9,188.8,167.9,2019-09-27,13:30:00,53
2304685,190.8,178.8,178.8,169.9,165.9,160.9,188.8,193.8,159.9,2019-09-27,13:45:00,53
2304686,178.8,178.8,169.9,165.9,160.9,188.8,193.8,191.8,154.9,2019-09-27,14:00:00,53
2304687,178.8,169.9,165.9,160.9,188.8,193.8,191.8,185.8,150.9,2019-09-27,14:15:00,53
2304688,169.9,165.9,160.9,188.8,193.8,191.8,185.8,167.9,156.9,2019-09-27,14:30:00,53