In [1]:
import pandas as pd

# Compare Folds Creation between Old and New Version for Horizon 2

In [2]:
# Load the parquet files
df_old_folds_file_h2 = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Compare_Folds_creation/old_version/windows_with_folds_horizon_2.parquet')
df_new_folds_file_h2 = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Compare_Folds_creation/new_version/windows_with_folds_horizon_2.parquet')

In [3]:
df_old_folds_file_h2

,x0,x1,x2,x3,x4,x5,x6,x7,y,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,99,92,86,85,85,87,88,93,134,LIB193263,train,train,val,train,test
1,92,86,85,85,87,88,93,106,165,LIB193263,train,train,val,train,test
2,86,85,85,87,88,93,106,134,187,LIB193263,train,train,val,train,test
3,85,85,87,88,93,106,134,165,206,LIB193263,train,train,val,train,test
4,85,87,88,93,106,134,165,187,223,LIB193263,train,train,val,train,test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19851235,208,206,191,170,155,148,145,141,169,LIB194166,train,train,test,train,train
19851236,206,191,170,155,148,145,141,143,206,LIB194166,train,train,test,train,train
19851237,191,170,155,148,145,141,143,169,215,LIB194166,train,train,test,train,train
19851238,170,155,148,145,141,143,169,206,204,LIB194166,train,train,test,train,train
19851239,155,148,145,141,143,169,206,215,199,LIB194166,train,train,test,train,train

In [5]:
df_new_folds_file_h2

,x0,x1,x2,x3,x4,x5,x6,x7,y,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,99,92,86,85,85,87,88,93,134,LIB193263,train,train,val,train,test
1,92,86,85,85,87,88,93,106,165,LIB193263,train,train,val,train,test
2,86,85,85,87,88,93,106,134,187,LIB193263,train,train,val,train,test
3,85,85,87,88,93,106,134,165,206,LIB193263,train,train,val,train,test
4,85,87,88,93,106,134,165,187,223,LIB193263,train,train,val,train,test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19851235,208,206,191,170,155,148,145,141,169,LIB194166,train,train,test,train,train
19851236,206,191,170,155,148,145,141,143,206,LIB194166,train,train,test,train,train
19851237,191,170,155,148,145,141,143,169,215,LIB194166,train,train,test,train,train
19851238,170,155,148,145,141,143,169,206,204,LIB194166,train,train,test,train,train
19851239,155,148,145,141,143,169,206,215,199,LIB194166,train,train,test,train,train

In [6]:
df_old_folds_file_h2.compare(df_new_folds_file_h2)

Empty DataFrame
Columns: []
Index: []

Both versions are identical for Horizon 2

# Compare Folds Creation between Old and New Version for Horizon 4

In [7]:
df_old_folds_file_h4 = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Compare_Folds_creation/old_version/windows_with_folds_horizon_4.parquet')
df_new_folds_file_h4 = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Compare_Folds_creation/new_version/windows_with_folds_horizon_4.parquet')

In [8]:
df_old_folds_file_h4

,x0,x1,x2,x3,x4,x5,x6,x7,y,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,99,92,86,85,85,87,88,93,187,LIB193263,train,test,train,train,train
1,92,86,85,85,87,88,93,106,206,LIB193263,train,test,train,train,train
2,86,85,85,87,88,93,106,134,223,LIB193263,train,test,train,train,train
3,85,85,87,88,93,106,134,165,234,LIB193263,train,test,train,train,train
4,85,87,88,93,106,134,165,187,236,LIB193263,train,test,train,train,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19421401,173,187,208,206,191,170,155,148,169,LIB194166,train,test,train,val,train
19421402,187,208,206,191,170,155,148,145,206,LIB194166,train,test,train,val,train
19421403,208,206,191,170,155,148,145,141,215,LIB194166,train,test,train,val,train
19421404,206,191,170,155,148,145,141,143,204,LIB194166,train,test,train,val,train
19421405,191,170,155,148,145,141,143,169,199,LIB194166,train,test,train,val,train

In [9]:
df_new_folds_file_h4

,x0,x1,x2,x3,x4,x5,x6,x7,y,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,99,92,86,85,85,87,88,93,187,LIB193263,train,test,train,train,train
1,92,86,85,85,87,88,93,106,206,LIB193263,train,test,train,train,train
2,86,85,85,87,88,93,106,134,223,LIB193263,train,test,train,train,train
3,85,85,87,88,93,106,134,165,234,LIB193263,train,test,train,train,train
4,85,87,88,93,106,134,165,187,236,LIB193263,train,test,train,train,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19421401,173,187,208,206,191,170,155,148,169,LIB194166,train,test,train,val,train
19421402,187,208,206,191,170,155,148,145,206,LIB194166,train,test,train,val,train
19421403,208,206,191,170,155,148,145,141,215,LIB194166,train,test,train,val,train
19421404,206,191,170,155,148,145,141,143,204,LIB194166,train,test,train,val,train
19421405,191,170,155,148,145,141,143,169,199,LIB194166,train,test,train,val,train

In [10]:
df_old_folds_file_h4.compare(df_new_folds_file_h4)

Empty DataFrame
Columns: []
Index: []

Both versions are identical for Horizon 4