In [1]:
import pandas as pd

In [2]:
df_diatrend_original = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/t1diabetesgranada/Final versions V4/Filtered_for_prediction/Glucose_measurements_FILTERED_2025-11-21.parquet')
df_diatrend_original

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,LIB193263,2020-06-09,19:08:00,99.0,2020-06-09 19:15:00,NaT
1,LIB193263,2020-06-09,19:23:00,92.0,2020-06-09 19:30:00,NaT
2,LIB193263,2020-06-09,19:38:00,86.0,2020-06-09 19:45:00,NaT
3,LIB193263,2020-06-09,19:53:00,85.0,2020-06-09 20:00:00,NaT
4,LIB193263,2020-06-09,20:08:00,85.0,2020-06-09 20:15:00,NaT
...,...,...,...,...,...,...
30477429,LIB194166,None,None,NaN,2022-03-17 04:00:00,NaT
30477430,LIB194166,None,None,NaN,2022-03-17 04:15:00,NaT
30477431,LIB194166,None,None,NaN,2022-03-17 04:30:00,NaT
30477432,LIB194166,None,None,NaN,2022-03-17 04:45:00,NaT
30477433,LIB194166,None,None,NaN,2022-03-17 05:00:00,NaT

In [3]:
# Lowercase the column names
df_diatrend_original.columns =  df_diatrend_original.columns.str.lower()
df_diatrend_original['patient_id'] = df_diatrend_original['patient_id'].astype(str)

In [4]:
df_diatrend_original_new = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/t1diabetesgranada/Final versions V4/Filtered_for_prediction/Glucose_measurements_T1DiabetesGranada_FILTERED_2026-03-27.parquet')
df_diatrend_original_new

,patient_id,measurement_date,measurement_time,measurement,15min,5min
0,LIB193263,2020-06-09,19:08:00,99,2020-06-09 19:15:00,NaT
1,LIB193263,2020-06-09,19:23:00,92,2020-06-09 19:30:00,NaT
2,LIB193263,2020-06-09,19:38:00,86,2020-06-09 19:45:00,NaT
3,LIB193263,2020-06-09,19:53:00,85,2020-06-09 20:00:00,NaT
4,LIB193263,2020-06-09,20:08:00,85,2020-06-09 20:15:00,NaT
...,...,...,...,...,...,...
30477429,LIB194166,None,None,<NA>,2022-03-17 04:00:00,NaT
30477430,LIB194166,None,None,<NA>,2022-03-17 04:15:00,NaT
30477431,LIB194166,None,None,<NA>,2022-03-17 04:30:00,NaT
30477432,LIB194166,None,None,<NA>,2022-03-17 04:45:00,NaT
30477433,LIB194166,None,None,<NA>,2022-03-17 05:00:00,NaT

In [5]:
df_diatrend_original_new['measurement'] = df_diatrend_original_new['measurement'].astype(float)
df_diatrend_original_new

,patient_id,measurement_date,measurement_time,measurement,15min,5min
0,LIB193263,2020-06-09,19:08:00,99.0,2020-06-09 19:15:00,NaT
1,LIB193263,2020-06-09,19:23:00,92.0,2020-06-09 19:30:00,NaT
2,LIB193263,2020-06-09,19:38:00,86.0,2020-06-09 19:45:00,NaT
3,LIB193263,2020-06-09,19:53:00,85.0,2020-06-09 20:00:00,NaT
4,LIB193263,2020-06-09,20:08:00,85.0,2020-06-09 20:15:00,NaT
...,...,...,...,...,...,...
30477429,LIB194166,None,None,NaN,2022-03-17 04:00:00,NaT
30477430,LIB194166,None,None,NaN,2022-03-17 04:15:00,NaT
30477431,LIB194166,None,None,NaN,2022-03-17 04:30:00,NaT
30477432,LIB194166,None,None,NaN,2022-03-17 04:45:00,NaT
30477433,LIB194166,None,None,NaN,2022-03-17 05:00:00,NaT

In [6]:
df_diatrend_original_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30477434 entries, 0 to 30477433
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   patient_id        object
 1   measurement_date  object
 2   measurement_time  object
 3   measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 1.4+ GB

In [11]:
# Get the rows differents between the two dataframes 
df_diff = pd.concat([df_diatrend_original, df_diatrend_original_new], axis=0)
df_diff

,patient_id,measurement_date,measurement_time,measurement,15min,5min
0,LIB193263,2020-06-09,19:08:00,99.0,2020-06-09 19:15:00,NaT
1,LIB193263,2020-06-09,19:23:00,92.0,2020-06-09 19:30:00,NaT
2,LIB193263,2020-06-09,19:38:00,86.0,2020-06-09 19:45:00,NaT
3,LIB193263,2020-06-09,19:53:00,85.0,2020-06-09 20:00:00,NaT
4,LIB193263,2020-06-09,20:08:00,85.0,2020-06-09 20:15:00,NaT
...,...,...,...,...,...,...
30477429,LIB194166,None,None,NaN,2022-03-17 04:00:00,NaT
30477430,LIB194166,None,None,NaN,2022-03-17 04:15:00,NaT
30477431,LIB194166,None,None,NaN,2022-03-17 04:30:00,NaT
30477432,LIB194166,None,None,NaN,2022-03-17 04:45:00,NaT
30477433,LIB194166,None,None,NaN,2022-03-17 05:00:00,NaT

In [12]:
df_diff.drop_duplicates(keep=False, inplace=True)
df_diff

Empty DataFrame
Columns: [patient_id, measurement_date, measurement_time, measurement, 15min, 5min]
Index: []

In [13]:
df_diff['patient_id'].value_counts()

Series([], Name: count, dtype: int64)