In [3]:
import os
import glob
import warnings
import pandas as pd

base_folder = 'c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/t1diabetesgranada/v4'
df = pd.read_parquet(os.path.join(base_folder, 'resampled_LIB193263.parquet'))
df

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,LIB193263,2020-06-09,19:08:00,99.0,2020-06-09 19:15:00,NaT
1,LIB193263,2020-06-09,19:23:00,92.0,2020-06-09 19:30:00,NaT
2,LIB193263,2020-06-09,19:38:00,86.0,2020-06-09 19:45:00,NaT
3,LIB193263,2020-06-09,19:53:00,85.0,2020-06-09 20:00:00,NaT
4,LIB193263,2020-06-09,20:08:00,85.0,2020-06-09 20:15:00,NaT
...,...,...,...,...,...,...
62217,LIB193263,2022-03-19,06:32:00,124.0,2022-03-19 06:30:00,NaT
62218,LIB193263,2022-03-19,06:47:00,124.0,2022-03-19 06:45:00,NaT
62219,LIB193263,2022-03-19,07:02:00,118.0,2022-03-19 07:00:00,NaT
62220,LIB193263,2022-03-19,07:17:00,110.0,2022-03-19 07:15:00,NaT
62221,LIB193263,2022-03-19,07:32:00,105.0,2022-03-19 07:30:00,NaT

In [6]:
import os
import glob
import warnings
import pandas as pd

# Carpeta base de DiaTrend
base_folder = 'c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/t1diabetesgranada/v4'


# Silenciar warnings de tipos mixtos en pandas
warnings.filterwarnings('ignore', category=pd.errors.DtypeWarning)

if not os.path.isdir(base_folder):
    print(f"No existe la carpeta {base_folder}, la salto.")
    
# 1) Concatenar resampled_{patient_id}.parquet
resampled_pattern = os.path.join(base_folder, 'resampled_*.parquet')
resampled_files = glob.glob(resampled_pattern)

dfs = [pd.read_parquet(f) for f in resampled_files]
df_resampled = pd.concat(dfs, ignore_index=True)
# df_resampled['Patient_ID'] = df_resampled['Patient_ID'].astype(int)
# df_resampled = df_resampled.sort_values(
#     by=['Patient_ID'],
#     ignore_index=True,
#     kind='mergesort'
# )
out_res = os.path.join(base_folder, f'Glucose_measurements_v4.parquet')

In [7]:
df_resampled

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,LIB193263,2020-06-09,19:08:00,99.0,2020-06-09 19:15:00,NaT
1,LIB193263,2020-06-09,19:23:00,92.0,2020-06-09 19:30:00,NaT
2,LIB193263,2020-06-09,19:38:00,86.0,2020-06-09 19:45:00,NaT
3,LIB193263,2020-06-09,19:53:00,85.0,2020-06-09 20:00:00,NaT
4,LIB193263,2020-06-09,20:08:00,85.0,2020-06-09 20:15:00,NaT
...,...,...,...,...,...,...
31706819,LIB194166,2022-03-17,15:08:00,169.0,2022-03-17 15:15:00,NaT
31706820,LIB194166,2022-03-17,15:23:00,206.0,2022-03-17 15:30:00,NaT
31706821,LIB194166,2022-03-17,15:38:00,215.0,2022-03-17 15:45:00,NaT
31706822,LIB194166,2022-03-17,15:53:00,204.0,2022-03-17 16:00:00,NaT
31706823,LIB194166,2022-03-17,16:08:00,199.0,2022-03-17 16:15:00,NaT

In [8]:
df_resampled.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)
df_resampled

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,LIB193263,2020-06-09,19:08:00,99.0,2020-06-09 19:15:00,NaT
1,LIB193263,2020-06-09,19:23:00,92.0,2020-06-09 19:30:00,NaT
2,LIB193263,2020-06-09,19:38:00,86.0,2020-06-09 19:45:00,NaT
3,LIB193263,2020-06-09,19:53:00,85.0,2020-06-09 20:00:00,NaT
4,LIB193263,2020-06-09,20:08:00,85.0,2020-06-09 20:15:00,NaT
...,...,...,...,...,...,...
31706819,LIB194166,None,None,NaN,2022-03-17 04:00:00,NaT
31706820,LIB194166,None,None,NaN,2022-03-17 04:15:00,NaT
31706821,LIB194166,None,None,NaN,2022-03-17 04:30:00,NaT
31706822,LIB194166,None,None,NaN,2022-03-17 04:45:00,NaT
31706823,LIB194166,None,None,NaN,2022-03-17 05:00:00,NaT

In [9]:
# df_resampled = df_resampled.drop(columns=['5min'])
df_resampled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31706824 entries, 0 to 31706823
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        object
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 1.4+ GB

In [10]:
df_resampled.to_parquet(out_res, index=False)
print(f"Concatenados {len(resampled_files)} archivos resampled en {out_res}")

Concatenados 736 archivos resampled en c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/t1diabetesgranada/v4\Glucose_measurements_v4.parquet