In [1]:
import pandas as pd

# DiaTrend

In [3]:
df_windows_horizon_4_diatrend = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/diatrend/files_for_crossvalidation/windows/windows_horizon_4.parquet')
df_windows_horizon_4_diatrend

          x0   x1   x2   x3   x4   x5   x6   x7    y  patient_id
0        160  162  167  150  164  147  130  137  143           1
1        177  176  195  194  153  117  100   94   92           1
2        176  195  194  153  117  100   94   83  106           1
3        195  194  153  117  100   94   83   74  122           1
4        194  153  117  100   94   83   74   81  147           1
...      ...  ...  ...  ...  ...  ...  ...  ...  ...         ...
2304684  207  190  178  178  169  165  160  188  167          53
2304685  190  178  178  169  165  160  188  193  159          53
2304686  178  178  169  165  160  188  193  191  154          53
2304687  178  169  165  160  188  193  191  185  150          53
2304688  169  165  160  188  193  191  185  167  156          53

[2304689 rows x 10 columns]

## Patient number

In [9]:
df_windows_horizon_4_diatrend['patient_id'].unique().shape

(51,)

In [4]:
target_diatrend = df_windows_horizon_4_diatrend['y']
target_diatrend

0          143
1           92
2          106
3          122
4          147
          ...
2304684    167
2304685    159
2304686    154
2304687    150
2304688    156
Name: y, Length: 2304689, dtype: int64

In [10]:
target_diatrend.describe().round(2)

count    2304689.00
mean         185.45
std           73.26
min           38.00
25%          130.00
50%          175.00
75%          230.00
max          401.00
Name: y, dtype: float64

## Range array creation

In [18]:
df_target_vector_diatrend_TBR_2 = target_diatrend[target_diatrend < 54]

df_target_vector_diatrend_TBR_1 = target_diatrend[(target_diatrend >= 54) & (target_diatrend < 70)]

df_target_vector_diatrend_TIR = target_diatrend[(target_diatrend >= 70) & (target_diatrend < 181)]

df_target_vector_diatrend_TAR_1 = target_diatrend[(target_diatrend >= 181) & (target_diatrend < 251)]

df_target_vector_diatrend_TAR_2 = target_diatrend[(target_diatrend >= 251)]

## Dataframe with stats 
Count, % Total, mean, std

In [33]:
df_stats_diatrend = pd.DataFrame(columns=['ENTIRE', 'TBR_2', 'TBR_1', 'TIR', 'TAR_1', 'TAR_2'], index=['Count', '% Total', 'Mean', 'Std'])
df_stats_diatrend.index.name = 'Stats'
df_stats_diatrend

        ENTIRE TBR_2 TBR_1  TIR TAR_1 TAR_2
Stats
Count      NaN   NaN   NaN  NaN   NaN   NaN
% Total    NaN   NaN   NaN  NaN   NaN   NaN
Mean       NaN   NaN   NaN  NaN   NaN   NaN
Std        NaN   NaN   NaN  NaN   NaN   NaN

In [34]:
# Fill the dataframe with the stats for each range with for loop
ranges = ['ENTIRE', 'TBR_2', 'TBR_1', 'TIR', 'TAR_1', 'TAR_2']
for range in ranges:
    if range == 'ENTIRE':
        data = target_diatrend
    else:
        data = eval(f'df_target_vector_diatrend_{range}')
    
    df_stats_diatrend.loc['Count', range] = data.shape[0]
    df_stats_diatrend.loc['% Total', range] = round((data.shape[0] / target_diatrend.shape[0]) * 100, 2)
    df_stats_diatrend.loc['Mean', range] = data.mean().round(2)
    df_stats_diatrend.loc['Std', range] = data.std().round(2)
    
df_stats_diatrend

          ENTIRE  TBR_2  TBR_1      TIR   TAR_1   TAR_2
Stats
Count    2304689  10016  32074  1178318  661270  423011
% Total    100.0   0.43   1.39    51.13   28.69   18.35
Mean      185.45  45.92  63.02   132.55  212.39  303.26
Std        73.26   5.09   4.41    28.93    19.9   43.44

In [36]:
# Transform dataframe to have percentaje of total and total in the same cell and mean and std in the same cell
df_stats_diatrend_combined = pd.DataFrame(columns=['ENTIRE', 'TBR_2', 'TBR_1', 'TIR', 'TAR_1', 'TAR_2'], index=['Count (%)', 'Mean ±Std'])
df_stats_diatrend_combined.index.name = 'Stats'
for range in ranges:
    count = df_stats_diatrend.loc['Count', range]
    percent_total = df_stats_diatrend.loc['% Total', range]
    mean = df_stats_diatrend.loc['Mean', range]
    std = df_stats_diatrend.loc['Std', range]
    
    df_stats_diatrend_combined.loc['Count (%)', range] = f'{count} ({percent_total}%)'
    df_stats_diatrend_combined.loc['Mean ±Std', range] = f'{mean} ±{std}'

df_stats_diatrend_combined

,ENTIRE,TBR_2,TBR_1,TIR,TAR_1,TAR_2
Stats,,,,,,
Count (%),2304689 (100.0%),10016 (0.43%),32074 (1.39%),1178318 (51.13%),661270 (28.69%),423011 (18.35%)
Mean ±Std,185.45 ±73.26,45.92 ±5.09,63.02 ±4.41,132.55 ±28.93,212.39 ±19.9,303.26 ±43.44

In [37]:
# Traspose the dataframe to have the ranges as index and stats as columns
df_stats_diatrend_combined_transposed = df_stats_diatrend_combined.T
df_stats_diatrend_combined_transposed

Stats          Count (%)      Mean ±Std
ENTIRE  2304689 (100.0%)  185.45 ±73.26
TBR_2      10016 (0.43%)    45.92 ±5.09
TBR_1      32074 (1.39%)    63.02 ±4.41
TIR     1178318 (51.13%)  132.55 ±28.93
TAR_1    661270 (28.69%)   212.39 ±19.9
TAR_2    423011 (18.35%)  303.26 ±43.44

# Replace BG

In [38]:
df_windows_horizon_4_replace = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/replace/files_for_crossvalidation/windows/windows_horizon_4.parquet')
df_windows_horizon_4_replace

          x0   x1   x2   x3   x4   x5   x6   x7    y  patient_id
0        161  157  165  156  140  113  111  116  173           2
1        157  165  156  140  113  111  116  132  159           2
2        165  156  140  113  111  116  132  158  160           2
3        156  140  113  111  116  132  158  189  141           2
4        140  113  111  116  132  158  189  173  179           2
...      ...  ...  ...  ...  ...  ...  ...  ...  ...         ...
3305406  162  162  163  159  142  132  146  183  209         293
3305407  162  163  159  142  132  146  183  208  198         293
3305408  163  159  142  132  146  183  208  227  190         293
3305409  159  142  132  146  183  208  227  225  186         293
3305410  142  132  146  183  208  227  225  209  172         293

[3305411 rows x 10 columns]

## Patient number

In [39]:
df_windows_horizon_4_replace['patient_id'].unique().shape

(223,)

In [40]:
target_replace = df_windows_horizon_4_replace['y']
target_replace

0          173
1          159
2          160
3          141
4          179
          ...
3305406    209
3305407    198
3305408    190
3305409    186
3305410    172
Name: y, Length: 3305411, dtype: int64

In [41]:
target_replace.describe().round(2)

count    3305411.00
mean         159.46
std           63.51
min           39.00
25%          112.00
50%          150.00
75%          197.00
max          401.00
Name: y, dtype: float64

## Range array creation

In [42]:
df_target_vector_replace_TBR_2 = target_replace[target_replace < 54]
df_target_vector_replace_TBR_1 = target_replace[(target_replace >= 54) & (target_replace < 70)]
df_target_vector_replace_TIR = target_replace[(target_replace >= 70) & (target_replace < 181)]
df_target_vector_replace_TAR_1 = target_replace[(target_replace >= 181) & (target_replace < 251)]
df_target_vector_replace_TAR_2 = target_replace[(target_replace >= 251)]

## Dataframe with stats
Count, % Total, mean, std

In [43]:
df_stats_replace = pd.DataFrame(columns=['ENTIRE', 'TBR_2', 'TBR_1', 'TIR', 'TAR_1', 'TAR_2'], index=['Count', '% Total', 'Mean', 'Std'])
df_stats_replace.index.name = 'Stats'
df_stats_replace

        ENTIRE TBR_2 TBR_1  TIR TAR_1 TAR_2
Stats
Count      NaN   NaN   NaN  NaN   NaN   NaN
% Total    NaN   NaN   NaN  NaN   NaN   NaN
Mean       NaN   NaN   NaN  NaN   NaN   NaN
Std        NaN   NaN   NaN  NaN   NaN   NaN

In [44]:
# Fill the dataframe with the stats for each range with for loop
ranges = ['ENTIRE', 'TBR_2', 'TBR_1', 'TIR', 'TAR_1', 'TAR_2']
for range in ranges:
    if range == 'ENTIRE':
        data = target_replace
    else:
        data = eval(f'df_target_vector_replace_{range}')
    
    df_stats_replace.loc['Count', range] = data.shape[0]
    df_stats_replace.loc['% Total', range] = round((data.shape[0] / target_replace.shape[0]) * 100, 2)
    df_stats_replace.loc['Mean', range] = data.mean().round(2)
    df_stats_replace.loc['Std', range] = data.std().round(2)
df_stats_replace

          ENTIRE  TBR_2  TBR_1      TIR   TAR_1   TAR_2
Stats
Count    3305411  28519  91511  2113225  770830  301326
% Total    100.0   0.86   2.77    63.93   23.32    9.12
Mean      159.46  46.33  62.83   127.64  209.96  293.49
Std        63.51   4.98   4.47    29.68    19.6   37.92

# T1DiabetesGranada

In [45]:
df_windows_horizon_4_granada = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/t1diabetesgranada/files_for_crossvalidation/windows/windows_horizon_4.parquet')
df_windows_horizon_4_granada

           x0   x1   x2   x3   x4   x5   x6   x7    y patient_id
0          99   92   86   85   85   87   88   93  187  LIB193263
1          92   86   85   85   87   88   93  106  206  LIB193263
2          86   85   85   87   88   93  106  134  223  LIB193263
3          85   85   87   88   93  106  134  165  234  LIB193263
4          85   87   88   93  106  134  165  187  236  LIB193263
...       ...  ...  ...  ...  ...  ...  ...  ...  ...        ...
19421401  173  187  208  206  191  170  155  148  169  LIB194166
19421402  187  208  206  191  170  155  148  145  206  LIB194166
19421403  208  206  191  170  155  148  145  141  215  LIB194166
19421404  206  191  170  155  148  145  141  143  204  LIB194166
19421405  191  170  155  148  145  141  143  169  199  LIB194166

[19421406 rows x 10 columns]

## Patient number

In [46]:
df_windows_horizon_4_granada['patient_id'].unique().shape

(643,)

In [47]:
target_granada = df_windows_horizon_4_granada['y']
target_granada

0           187
1           206
2           223
3           234
4           236
           ...
19421401    169
19421402    206
19421403    215
19421404    204
19421405    199
Name: y, Length: 19421406, dtype: int64

In [48]:
target_granada.describe().round(2)

count    19421406.00
mean          163.44
std            70.21
min            40.00
25%           111.00
50%           152.00
75%           204.00
max           500.00
Name: y, dtype: float64

## Range array creation

In [49]:
df_target_vector_granada_TBR_2 = target_granada[target_granada < 54]
df_target_vector_granada_TBR_1 = target_granada[(target_granada >= 54) & (target_granada < 70)]
df_target_vector_granada_TIR = target_granada[(target_granada >= 70) & (target_granada < 181)]
df_target_vector_granada_TAR_1 = target_granada[(target_granada >= 181) & (target_granada < 251)]
df_target_vector_granada_TAR_2 = target_granada[(target_granada >= 251)]

## Dataframe with stats
Count, % Total, mean, std

In [50]:
df_stats_granada = pd.DataFrame(columns=['ENTIRE', 'TBR_2', 'TBR_1', 'TIR', 'TAR_1', 'TAR_2'], index=['Count', '% Total', 'Mean', 'Std'])
df_stats_granada.index.name = 'Stats'
df_stats_granada

        ENTIRE TBR_2 TBR_1  TIR TAR_1 TAR_2
Stats
Count      NaN   NaN   NaN  NaN   NaN   NaN
% Total    NaN   NaN   NaN  NaN   NaN   NaN
Mean       NaN   NaN   NaN  NaN   NaN   NaN
Std        NaN   NaN   NaN  NaN   NaN   NaN

In [51]:
# Fill the dataframe with the stats for each range with for loop
ranges = ['ENTIRE', 'TBR_2', 'TBR_1', 'TIR', 'TAR_1', 'TAR_2']
for range in ranges:
    if range == 'ENTIRE':
        data = target_granada
    else:
        data = eval(f'df_target_vector_granada_{range}')
    
    df_stats_granada.loc['Count', range] = data.shape[0]
    df_stats_granada.loc['% Total', range] = round((data.shape[0] / target_granada.shape[0]) * 100, 2)
    df_stats_granada.loc['Mean', range] = data.mean().round(2)
    df_stats_granada.loc['Std', range] = data.std().round(2)

df_stats_granada

           ENTIRE   TBR_2   TBR_1       TIR    TAR_1    TAR_2
Stats
Count    19421406  182690  740462  11695775  4588512  2213967
% Total     100.0    0.94    3.81     60.22    23.63     11.4
Mean       163.44   48.75    62.1    126.91    210.9   301.43
Std         70.21    5.09    4.62      30.0    19.73    48.87

# Merge results
the three dataframes verticaly adding the dataset name as initial column

In [58]:
df_stats_diatrend['Dataset'] = 'DiaTrend'
df_stats_replace['Dataset'] = 'Replace'
df_stats_granada['Dataset'] = 'T1DiabetesGranada'
df_stats_combined = pd.concat([df_stats_diatrend, df_stats_replace, df_stats_granada])
df_stats_combined

,ENTIRE,TBR_2,TBR_1,TIR,TAR_1,TAR_2,Dataset
Stats,,,,,,,
Count,2304689,10016,32074,1178318,661270,423011,DiaTrend
% Total,100.0,0.43,1.39,51.13,28.69,18.35,DiaTrend
Mean,185.45,45.92,63.02,132.55,212.39,303.26,DiaTrend
Std,73.26,5.09,4.41,28.93,19.9,43.44,DiaTrend
Count,3305411,28519,91511,2113225,770830,301326,Replace
% Total,100.0,0.86,2.77,63.93,23.32,9.12,Replace
Mean,159.46,46.33,62.83,127.64,209.96,293.49,Replace
Std,63.51,4.98,4.47,29.68,19.6,37.92,Replace
Count,19421406,182690,740462,11695775,4588512,2213967,T1DiabetesGranada
% Total,100.0,0.94,3.81,60.22,23.63,11.4,T1DiabetesGranada
Mean,163.44,48.75,62.1,126.91,210.9,301.43,T1DiabetesGranada
Std,70.21,5.09,4.62,30.0,19.73,48.87,T1DiabetesGranada

In [59]:
# Transform index to column
df_stats_combined.reset_index(inplace=True)
# Put dataset column in the first position
cols = df_stats_combined.columns.tolist()
cols = cols[-1:] + cols[:-1]
df_stats_combined = df_stats_combined[cols]
df_stats_combined

,Dataset,Stats,ENTIRE,TBR_2,TBR_1,TIR,TAR_1,TAR_2
0,DiaTrend,Count,2304689,10016,32074,1178318,661270,423011
1,DiaTrend,% Total,100.0,0.43,1.39,51.13,28.69,18.35
2,DiaTrend,Mean,185.45,45.92,63.02,132.55,212.39,303.26
3,DiaTrend,Std,73.26,5.09,4.41,28.93,19.9,43.44
4,Replace,Count,3305411,28519,91511,2113225,770830,301326
5,Replace,% Total,100.0,0.86,2.77,63.93,23.32,9.12
6,Replace,Mean,159.46,46.33,62.83,127.64,209.96,293.49
7,Replace,Std,63.51,4.98,4.47,29.68,19.6,37.92
8,T1DiabetesGranada,Count,19421406,182690,740462,11695775,4588512,2213967
9,T1DiabetesGranada,% Total,100.0,0.94,3.81,60.22,23.63,11.4
10,T1DiabetesGranada,Mean,163.44,48.75,62.1,126.91,210.9,301.43
11,T1DiabetesGranada,Std,70.21,5.09,4.62,30.0,19.73,48.87

In [60]:
# Save as excel file
df_stats_combined.to_excel('stats_after_windowing_Three_datasets.xlsx', index=False)