In [1]:
import pandas as pd

# Diatrend

In [29]:
df_diatrend_original = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/diatrend/Final_versions_V4/Filtered_for_prediction/Glucose_measurements_FILTERED_2025-11-20.parquet')
df_diatrend_original

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,1,2015-12-01,21:01:07,160.0,2015-12-01 21:00:00,2015-12-01 21:00:00
1,1,2015-12-01,21:06:07,161.0,NaT,2015-12-01 21:05:00
2,1,2015-12-01,21:11:08,165.0,NaT,2015-12-01 21:10:00
3,1,2015-12-01,21:16:08,162.0,2015-12-01 21:15:00,2015-12-01 21:15:00
4,1,2015-12-01,21:21:07,163.0,NaT,2015-12-01 21:20:00
...,...,...,...,...,...,...
9155084,53,None,None,NaN,NaT,2019-09-27 04:40:00
9155085,53,None,None,NaN,NaT,2019-09-27 05:25:00
9155086,53,None,None,NaN,2019-09-27 05:30:00,2019-09-27 05:30:00
9155087,53,None,None,NaN,NaT,2019-09-27 05:35:00
9155088,53,None,None,NaN,NaT,2019-09-27 05:40:00

In [30]:
df_diatrend_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9155089 entries, 0 to 9155088
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int64
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 419.1+ MB

## Round Measurement to 0 decimals and change Patient_ID to string

In [43]:
df_diatrend_round_0_id_str_measurement_int = df_diatrend_original.copy()
df_diatrend_round_0_id_str_measurement_int['Patient_ID'] = df_diatrend_round_0_id_str_measurement_int['Patient_ID'].astype(str)
df_diatrend_round_0_id_str_measurement_int['Measurement'] = df_diatrend_round_0_id_str_measurement_int['Measurement'].round(0).astype('Int16')
df_diatrend_round_0_id_str_measurement_int

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,1,2015-12-01,21:01:07,160,2015-12-01 21:00:00,2015-12-01 21:00:00
1,1,2015-12-01,21:06:07,161,NaT,2015-12-01 21:05:00
2,1,2015-12-01,21:11:08,165,NaT,2015-12-01 21:10:00
3,1,2015-12-01,21:16:08,162,2015-12-01 21:15:00,2015-12-01 21:15:00
4,1,2015-12-01,21:21:07,163,NaT,2015-12-01 21:20:00
...,...,...,...,...,...,...
9155084,53,None,None,<NA>,NaT,2019-09-27 04:40:00
9155085,53,None,None,<NA>,NaT,2019-09-27 05:25:00
9155086,53,None,None,<NA>,2019-09-27 05:30:00,2019-09-27 05:30:00
9155087,53,None,None,<NA>,NaT,2019-09-27 05:35:00
9155088,53,None,None,<NA>,NaT,2019-09-27 05:40:00

## Lowercase column names

In [46]:
df_diatrend_round_0_id_str_measurement_int.columns = df_diatrend_round_0_id_str_measurement_int.columns.str.lower()
df_diatrend_round_0_id_str_measurement_int

,patient_id,measurement_date,measurement_time,measurement,15min,5min
0,1,2015-12-01,21:01:07,160,2015-12-01 21:00:00,2015-12-01 21:00:00
1,1,2015-12-01,21:06:07,161,NaT,2015-12-01 21:05:00
2,1,2015-12-01,21:11:08,165,NaT,2015-12-01 21:10:00
3,1,2015-12-01,21:16:08,162,2015-12-01 21:15:00,2015-12-01 21:15:00
4,1,2015-12-01,21:21:07,163,NaT,2015-12-01 21:20:00
...,...,...,...,...,...,...
9155084,53,None,None,<NA>,NaT,2019-09-27 04:40:00
9155085,53,None,None,<NA>,NaT,2019-09-27 05:25:00
9155086,53,None,None,<NA>,2019-09-27 05:30:00,2019-09-27 05:30:00
9155087,53,None,None,<NA>,NaT,2019-09-27 05:35:00
9155088,53,None,None,<NA>,NaT,2019-09-27 05:40:00

In [47]:
df_diatrend_round_0_id_str_measurement_int.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9155089 entries, 0 to 9155088
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   patient_id        object
 1   measurement_date  object
 2   measurement_time  object
 3   measurement       Int16
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: Int16(1), datetime64[ns](2), object(3)
memory usage: 375.4+ MB

## Save as parquet

In [48]:
df_diatrend_round_0_id_str_measurement_int.to_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/diatrend/Final_versions_V4/Filtered_for_prediction/Glucose_measurements_DiaTrend_FILTERED_2026-03-27.parquet')

The changes made to the original DataFrame include:
1. **Patient_ID**: The `Patient_ID` column was converted from its original data type (likely an integer) to a string. This allows for better handling of patient identifiers, especially if they are not purely numeric or if leading zeros are important.
2. **Measurement**: The `Measurement` column was rounded to 0 decimal places and converted to an integer type (`Int16`). 
3. **Column Names**: The column names were converted to lowercase.

# REPLACE-BG
The same as above but for the REPLACE-BG dataset.

In [52]:
df_replace_bg_original = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/replace/Final_versions_V4/Filtered_for_prediction/Glucose_measurements_FILTERED_2025-11-19.parquet')
df_replace_bg_original

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,2,2000-03-08,00:04:50,166.0,NaT,2000-03-08 00:05:00
1,2,2000-03-08,00:09:50,169.0,NaT,2000-03-08 00:10:00
2,2,2000-03-08,00:14:50,161.0,2000-03-08 00:15:00,2000-03-08 00:15:00
3,2,2000-03-08,00:19:50,158.0,NaT,2000-03-08 00:20:00
4,2,2000-03-08,00:24:50,157.0,NaT,2000-03-08 00:25:00
...,...,...,...,...,...,...
11579403,293,None,None,NaN,NaT,2000-07-09 16:35:00
11579404,293,None,None,NaN,NaT,2000-07-10 12:25:00
11579405,293,None,None,NaN,2000-07-10 12:30:00,2000-07-10 12:30:00
11579406,293,None,None,NaN,NaT,2000-07-10 12:35:00
11579407,293,None,None,NaN,NaT,2000-07-11 07:20:00

In [53]:
df_replace_bg_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11579408 entries, 0 to 11579407
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int32
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int32(1), object(2)
memory usage: 485.9+ MB

## Round Measurement to 0 decimals and change Patient_ID to string

In [54]:
df_replace_bg_round_0_id_str_measurement_int = df_replace_bg_original.copy()
df_replace_bg_round_0_id_str_measurement_int['Patient_ID'] = df_replace_bg_round_0_id_str_measurement_int['Patient_ID'].astype(str)
df_replace_bg_round_0_id_str_measurement_int['Measurement'] = df_replace_bg_round_0_id_str_measurement_int['Measurement'].round(0).astype('Int16')
df_replace_bg_round_0_id_str_measurement_int

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,2,2000-03-08,00:04:50,166,NaT,2000-03-08 00:05:00
1,2,2000-03-08,00:09:50,169,NaT,2000-03-08 00:10:00
2,2,2000-03-08,00:14:50,161,2000-03-08 00:15:00,2000-03-08 00:15:00
3,2,2000-03-08,00:19:50,158,NaT,2000-03-08 00:20:00
4,2,2000-03-08,00:24:50,157,NaT,2000-03-08 00:25:00
...,...,...,...,...,...,...
11579403,293,None,None,<NA>,NaT,2000-07-09 16:35:00
11579404,293,None,None,<NA>,NaT,2000-07-10 12:25:00
11579405,293,None,None,<NA>,2000-07-10 12:30:00,2000-07-10 12:30:00
11579406,293,None,None,<NA>,NaT,2000-07-10 12:35:00
11579407,293,None,None,<NA>,NaT,2000-07-11 07:20:00

In [55]:
df_replace_bg_round_0_id_str_measurement_int.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11579408 entries, 0 to 11579407
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        object
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       Int16
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: Int16(1), datetime64[ns](2), object(3)
memory usage: 474.8+ MB

## Lowercase column names

In [56]:
df_replace_bg_round_0_id_str_measurement_int.columns = df_replace_bg_round_0_id_str_measurement_int.columns.str.lower()
df_replace_bg_round_0_id_str_measurement_int

,patient_id,measurement_date,measurement_time,measurement,15min,5min
0,2,2000-03-08,00:04:50,166,NaT,2000-03-08 00:05:00
1,2,2000-03-08,00:09:50,169,NaT,2000-03-08 00:10:00
2,2,2000-03-08,00:14:50,161,2000-03-08 00:15:00,2000-03-08 00:15:00
3,2,2000-03-08,00:19:50,158,NaT,2000-03-08 00:20:00
4,2,2000-03-08,00:24:50,157,NaT,2000-03-08 00:25:00
...,...,...,...,...,...,...
11579403,293,None,None,<NA>,NaT,2000-07-09 16:35:00
11579404,293,None,None,<NA>,NaT,2000-07-10 12:25:00
11579405,293,None,None,<NA>,2000-07-10 12:30:00,2000-07-10 12:30:00
11579406,293,None,None,<NA>,NaT,2000-07-10 12:35:00
11579407,293,None,None,<NA>,NaT,2000-07-11 07:20:00

## Save as parquet

In [57]:
df_replace_bg_round_0_id_str_measurement_int.to_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/replace/Final_versions_V4/Filtered_for_prediction/Glucose_measurements_REPLACE-BG_FILTERED_2026-03-27.parquet')

# T1DiabetesGranada
The same as above but for the T1DiabetesGranada dataset.

In [1]:
import pandas as pd
df_t1diabetes_granada_original = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/t1diabetesgranada/Final versions V4/Filtered_for_prediction/Glucose_measurements_FILTERED_2025-11-21.parquet')
df_t1diabetes_granada_original

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,LIB193263,2020-06-09,19:08:00,99.0,2020-06-09 19:15:00,NaT
1,LIB193263,2020-06-09,19:23:00,92.0,2020-06-09 19:30:00,NaT
2,LIB193263,2020-06-09,19:38:00,86.0,2020-06-09 19:45:00,NaT
3,LIB193263,2020-06-09,19:53:00,85.0,2020-06-09 20:00:00,NaT
4,LIB193263,2020-06-09,20:08:00,85.0,2020-06-09 20:15:00,NaT
...,...,...,...,...,...,...
30477429,LIB194166,None,None,NaN,2022-03-17 04:00:00,NaT
30477430,LIB194166,None,None,NaN,2022-03-17 04:15:00,NaT
30477431,LIB194166,None,None,NaN,2022-03-17 04:30:00,NaT
30477432,LIB194166,None,None,NaN,2022-03-17 04:45:00,NaT
30477433,LIB194166,None,None,NaN,2022-03-17 05:00:00,NaT

In [2]:
df_t1diabetes_granada_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30477434 entries, 0 to 30477433
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        object
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 1.4+ GB

## Round Measurement to 0 decimals

In [5]:
df_t1diabetes_granada_round_0_measurement_int = df_t1diabetes_granada_original.copy()
df_t1diabetes_granada_round_0_measurement_int['Measurement'] = df_t1diabetes_granada_round_0_measurement_int['Measurement'].round(0).astype('Int16')
df_t1diabetes_granada_round_0_measurement_int

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,LIB193263,2020-06-09,19:08:00,99,2020-06-09 19:15:00,NaT
1,LIB193263,2020-06-09,19:23:00,92,2020-06-09 19:30:00,NaT
2,LIB193263,2020-06-09,19:38:00,86,2020-06-09 19:45:00,NaT
3,LIB193263,2020-06-09,19:53:00,85,2020-06-09 20:00:00,NaT
4,LIB193263,2020-06-09,20:08:00,85,2020-06-09 20:15:00,NaT
...,...,...,...,...,...,...
30477429,LIB194166,None,None,<NA>,2022-03-17 04:00:00,NaT
30477430,LIB194166,None,None,<NA>,2022-03-17 04:15:00,NaT
30477431,LIB194166,None,None,<NA>,2022-03-17 04:30:00,NaT
30477432,LIB194166,None,None,<NA>,2022-03-17 04:45:00,NaT
30477433,LIB194166,None,None,<NA>,2022-03-17 05:00:00,NaT

In [6]:
df_t1diabetes_granada_round_0_measurement_int.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30477434 entries, 0 to 30477433
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        object
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       Int16
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: Int16(1), datetime64[ns](2), object(3)
memory usage: 1.2+ GB

## Lowercase column names

In [7]:
df_t1diabetes_granada_round_0_measurement_int.columns = df_t1diabetes_granada_round_0_measurement_int.columns.str.lower()
df_t1diabetes_granada_round_0_measurement_int

,patient_id,measurement_date,measurement_time,measurement,15min,5min
0,LIB193263,2020-06-09,19:08:00,99,2020-06-09 19:15:00,NaT
1,LIB193263,2020-06-09,19:23:00,92,2020-06-09 19:30:00,NaT
2,LIB193263,2020-06-09,19:38:00,86,2020-06-09 19:45:00,NaT
3,LIB193263,2020-06-09,19:53:00,85,2020-06-09 20:00:00,NaT
4,LIB193263,2020-06-09,20:08:00,85,2020-06-09 20:15:00,NaT
...,...,...,...,...,...,...
30477429,LIB194166,None,None,<NA>,2022-03-17 04:00:00,NaT
30477430,LIB194166,None,None,<NA>,2022-03-17 04:15:00,NaT
30477431,LIB194166,None,None,<NA>,2022-03-17 04:30:00,NaT
30477432,LIB194166,None,None,<NA>,2022-03-17 04:45:00,NaT
30477433,LIB194166,None,None,<NA>,2022-03-17 05:00:00,NaT

## Save as parquet

In [9]:
df_t1diabetes_granada_round_0_measurement_int.to_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/t1diabetesgranada/Final versions V4/Filtered_for_prediction/Glucose_measurements_T1DiabetesGranada_FILTERED_2026-03-27.parquet')

,patient_id,measurement_date,measurement_time,measurement,15min,5min
0,LIB193263,2020-06-09,19:08:00,99,2020-06-09 19:15:00,NaT
1,LIB193263,2020-06-09,19:23:00,92,2020-06-09 19:30:00,NaT
2,LIB193263,2020-06-09,19:38:00,86,2020-06-09 19:45:00,NaT
3,LIB193263,2020-06-09,19:53:00,85,2020-06-09 20:00:00,NaT
4,LIB193263,2020-06-09,20:08:00,85,2020-06-09 20:15:00,NaT
...,...,...,...,...,...,...
30477429,LIB194166,None,None,<NA>,2022-03-17 04:00:00,NaT
30477430,LIB194166,None,None,<NA>,2022-03-17 04:15:00,NaT
30477431,LIB194166,None,None,<NA>,2022-03-17 04:30:00,NaT
30477432,LIB194166,None,None,<NA>,2022-03-17 04:45:00,NaT
30477433,LIB194166,None,None,<NA>,2022-03-17 05:00:00,NaT