In [1]:
import pandas as pd

In [11]:
df1 = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Glucose_prediction_2026/Main_repo/Data_test/folds/windows_with_5folds_DiaTrend_PH8.parquet')
df1 = df1.sort_values(by=['patient_id', 'x_date_7', 'x_time_7']).reset_index(drop=True)
df1

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,fold0,fold1,fold2,fold3,fold4
0,177.0,176.0,195.0,194.0,153.0,117.0,100.0,94.0,163.0,2015-12-04,20:45:00,1,test,train,train,train,train
1,176.0,195.0,194.0,153.0,117.0,100.0,94.0,83.0,164.0,2015-12-04,21:00:00,1,test,train,train,train,train
2,195.0,194.0,153.0,117.0,100.0,94.0,83.0,74.0,159.0,2015-12-04,21:15:00,1,test,train,train,train,train
3,194.0,153.0,117.0,100.0,94.0,83.0,74.0,81.0,215.0,2015-12-04,21:30:00,1,test,train,train,train,train
4,153.0,117.0,100.0,94.0,83.0,74.0,81.0,92.0,257.0,2015-12-04,21:45:00,1,test,train,train,train,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2269226,245.0,222.0,182.0,175.0,153.0,120.0,114.0,119.0,121.0,2022-06-28,21:00:00,9,test,val,train,train,train
2269227,222.0,182.0,175.0,153.0,120.0,114.0,119.0,108.0,120.0,2022-06-28,21:15:00,9,test,val,train,train,train
2269228,182.0,175.0,153.0,120.0,114.0,119.0,108.0,102.0,126.0,2022-06-28,21:30:00,9,test,val,train,train,train
2269229,175.0,153.0,120.0,114.0,119.0,108.0,102.0,89.0,152.0,2022-06-28,21:45:00,9,test,val,train,train,train
2269230,153.0,120.0,114.0,119.0,108.0,102.0,89.0,83.0,164.0,2022-06-28,22:00:00,9,test,val,train,train,train

In [12]:
df2 = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/diatrend/Final_versions_V4/Filtered_for_prediction/windows/extra_fields/5folds/windows_with_5folds_DiaTrend_PH8.parquet')
df2['patient_id'] = df2['patient_id'].astype(str)
df2 = df2.sort_values(by=['patient_id', 'x_date_7', 'x_time_7']).reset_index(drop=True)
df2 = df2.round(0)
df2

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,177.0,176.0,195.0,194.0,153.0,117.0,100.0,94.0,163.0,2015-12-04,20:45:00,1,test,train,train,train,train
1,176.0,195.0,194.0,153.0,117.0,100.0,94.0,83.0,164.0,2015-12-04,21:00:00,1,test,train,train,train,train
2,195.0,194.0,153.0,117.0,100.0,94.0,83.0,74.0,159.0,2015-12-04,21:15:00,1,test,train,train,train,train
3,194.0,153.0,117.0,100.0,94.0,83.0,74.0,81.0,215.0,2015-12-04,21:30:00,1,test,train,train,train,train
4,153.0,117.0,100.0,94.0,83.0,74.0,81.0,92.0,257.0,2015-12-04,21:45:00,1,test,train,train,train,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2269226,245.0,222.0,182.0,175.0,153.0,120.0,114.0,119.0,121.0,2022-06-28,21:00:00,9,test,val,train,train,train
2269227,222.0,182.0,175.0,153.0,120.0,114.0,119.0,108.0,120.0,2022-06-28,21:15:00,9,test,val,train,train,train
2269228,182.0,175.0,153.0,120.0,114.0,119.0,108.0,102.0,126.0,2022-06-28,21:30:00,9,test,val,train,train,train
2269229,175.0,153.0,120.0,114.0,119.0,108.0,102.0,89.0,152.0,2022-06-28,21:45:00,9,test,val,train,train,train
2269230,153.0,120.0,114.0,119.0,108.0,102.0,89.0,83.0,164.0,2022-06-28,22:00:00,9,test,val,train,train,train

In [16]:
df1.columns = df2.columns
df1

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,177.0,176.0,195.0,194.0,153.0,117.0,100.0,94.0,163.0,2015-12-04,20:45:00,1,test,train,train,train,train
1,176.0,195.0,194.0,153.0,117.0,100.0,94.0,83.0,164.0,2015-12-04,21:00:00,1,test,train,train,train,train
2,195.0,194.0,153.0,117.0,100.0,94.0,83.0,74.0,159.0,2015-12-04,21:15:00,1,test,train,train,train,train
3,194.0,153.0,117.0,100.0,94.0,83.0,74.0,81.0,215.0,2015-12-04,21:30:00,1,test,train,train,train,train
4,153.0,117.0,100.0,94.0,83.0,74.0,81.0,92.0,257.0,2015-12-04,21:45:00,1,test,train,train,train,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2269226,245.0,222.0,182.0,175.0,153.0,120.0,114.0,119.0,121.0,2022-06-28,21:00:00,9,test,val,train,train,train
2269227,222.0,182.0,175.0,153.0,120.0,114.0,119.0,108.0,120.0,2022-06-28,21:15:00,9,test,val,train,train,train
2269228,182.0,175.0,153.0,120.0,114.0,119.0,108.0,102.0,126.0,2022-06-28,21:30:00,9,test,val,train,train,train
2269229,175.0,153.0,120.0,114.0,119.0,108.0,102.0,89.0,152.0,2022-06-28,21:45:00,9,test,val,train,train,train
2269230,153.0,120.0,114.0,119.0,108.0,102.0,89.0,83.0,164.0,2022-06-28,22:00:00,9,test,val,train,train,train

In [18]:
# Compare the two DataFrames
df1.compare(df2)

Empty DataFrame
Columns: []
Index: []

In [14]:
df1.columns

Index(['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'y', 'x_date_7',
       'x_time_7', 'patient_id', 'fold0', 'fold1', 'fold2', 'fold3', 'fold4'],
      dtype='object')

In [15]:
df2.columns

Index(['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'y', 'x_date_7',
       'x_time_7', 'patient_id', 'fold_0', 'fold_1', 'fold_2', 'fold_3',
       'fold_4'],
      dtype='object')

In [19]:
df4 = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Glucose_prediction_2026/Main_repo/Data_test/windows/windows_horizon_DiaTrend_8.parquet')
df4 = df4.sort_values(by=['patient_id', 'x_date_7', 'x_time_7']).reset_index(drop=True)
df4

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id
0,177.0,176.0,195.0,194.0,153.0,117.0,100.0,94.0,163.0,2015-12-04,20:45:00,1
1,176.0,195.0,194.0,153.0,117.0,100.0,94.0,83.0,164.0,2015-12-04,21:00:00,1
2,195.0,194.0,153.0,117.0,100.0,94.0,83.0,74.0,159.0,2015-12-04,21:15:00,1
3,194.0,153.0,117.0,100.0,94.0,83.0,74.0,81.0,215.0,2015-12-04,21:30:00,1
4,153.0,117.0,100.0,94.0,83.0,74.0,81.0,92.0,257.0,2015-12-04,21:45:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2269226,245.0,222.0,182.0,175.0,153.0,120.0,114.0,119.0,121.0,2022-06-28,21:00:00,9
2269227,222.0,182.0,175.0,153.0,120.0,114.0,119.0,108.0,120.0,2022-06-28,21:15:00,9
2269228,182.0,175.0,153.0,120.0,114.0,119.0,108.0,102.0,126.0,2022-06-28,21:30:00,9
2269229,175.0,153.0,120.0,114.0,119.0,108.0,102.0,89.0,152.0,2022-06-28,21:45:00,9
2269230,153.0,120.0,114.0,119.0,108.0,102.0,89.0,83.0,164.0,2022-06-28,22:00:00,9

In [22]:
df5 = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/diatrend/Final_versions_V4/Filtered_for_prediction/windows/extra_fields/windows_DiaTrend_PH8.parquet')
df5['patient_id'] = df5['patient_id'].astype(str)
df5 = df5.sort_values(by=['patient_id', 'x_date_7', 'x_time_7']).reset_index(drop=True)
df5 = df5.round(0) 
df5

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id
0,177.0,176.0,195.0,194.0,153.0,117.0,100.0,94.0,163.0,2015-12-04,20:45:00,1
1,176.0,195.0,194.0,153.0,117.0,100.0,94.0,83.0,164.0,2015-12-04,21:00:00,1
2,195.0,194.0,153.0,117.0,100.0,94.0,83.0,74.0,159.0,2015-12-04,21:15:00,1
3,194.0,153.0,117.0,100.0,94.0,83.0,74.0,81.0,215.0,2015-12-04,21:30:00,1
4,153.0,117.0,100.0,94.0,83.0,74.0,81.0,92.0,257.0,2015-12-04,21:45:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2269226,245.0,222.0,182.0,175.0,153.0,120.0,114.0,119.0,121.0,2022-06-28,21:00:00,9
2269227,222.0,182.0,175.0,153.0,120.0,114.0,119.0,108.0,120.0,2022-06-28,21:15:00,9
2269228,182.0,175.0,153.0,120.0,114.0,119.0,108.0,102.0,126.0,2022-06-28,21:30:00,9
2269229,175.0,153.0,120.0,114.0,119.0,108.0,102.0,89.0,152.0,2022-06-28,21:45:00,9
2269230,153.0,120.0,114.0,119.0,108.0,102.0,89.0,83.0,164.0,2022-06-28,22:00:00,9

In [23]:
df5.compare(df4)

Empty DataFrame
Columns: []
Index: []

In [36]:
df4['15min']

0         2015-12-01 21:00:00
1                         NaT
2                         NaT
3         2015-12-01 21:15:00
4                         NaT
                  ...
9155084                   NaT
9155085                   NaT
9155086   2019-09-27 05:30:00
9155087                   NaT
9155088                   NaT
Name: 15min, Length: 9155089, dtype: datetime64[ns]

In [37]:
df_null = df4[df4['15min'].isna()]
df_null

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
1,1,2015-12-01,21:06:07,161.0,NaT,2015-12-01 21:05:00
2,1,2015-12-01,21:11:08,165.0,NaT,2015-12-01 21:10:00
4,1,2015-12-01,21:21:07,163.0,NaT,2015-12-01 21:20:00
5,1,2015-12-01,21:26:07,166.0,NaT,2015-12-01 21:25:00
7,1,2015-12-01,21:36:06,164.0,NaT,2015-12-01 21:35:00
...,...,...,...,...,...,...
9155083,53,None,None,NaN,NaT,2019-09-27 04:35:00
9155084,53,None,None,NaN,NaT,2019-09-27 04:40:00
9155085,53,None,None,NaN,NaT,2019-09-27 05:25:00
9155087,53,None,None,NaN,NaT,2019-09-27 05:35:00
9155088,53,None,None,NaN,NaT,2019-09-27 05:40:00

In [22]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9155089 entries, 0 to 9155088
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int64
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 419.1+ MB

In [23]:

print(f"Max: {df1['measurement'].max()}")
print(f"Min: {df1['measurement'].min()}")

Max: 401
Min: 39

In [4]:
df1[(df1['fold_0'] == 'test')]

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
664203,134.0,123.0,116.0,113.0,112.0,111.0,109.0,129.0,114.0,2017-11-10,12:30:00,6,test,train,train,train,train
664204,123.0,116.0,113.0,112.0,111.0,109.0,129.0,97.0,129.0,2017-11-10,12:45:00,6,test,train,train,train,train
664205,116.0,113.0,112.0,111.0,109.0,129.0,97.0,114.0,150.0,2017-11-10,13:00:00,6,test,train,train,train,train
664206,113.0,112.0,111.0,109.0,129.0,97.0,114.0,129.0,131.0,2017-11-10,13:15:00,6,test,train,train,train,train
664207,112.0,111.0,109.0,129.0,97.0,114.0,129.0,150.0,119.0,2017-11-10,13:30:00,6,test,train,train,train,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2322819,178.8,178.8,169.9,165.9,160.9,188.8,193.8,191.8,167.9,2019-09-27,14:00:00,53,test,val,val,val,val
2322820,178.8,169.9,165.9,160.9,188.8,193.8,191.8,185.8,159.9,2019-09-27,14:15:00,53,test,val,val,val,val
2322821,169.9,165.9,160.9,188.8,193.8,191.8,185.8,167.9,154.9,2019-09-27,14:30:00,53,test,val,val,val,val
2322822,165.9,160.9,188.8,193.8,191.8,185.8,167.9,159.9,150.9,2019-09-27,14:45:00,53,test,val,val,val,val
2322823,160.9,188.8,193.8,191.8,185.8,167.9,159.9,154.9,156.9,2019-09-27,15:00:00,53,test,val,val,val,val

In [3]:
df2 = pd.read_parquet('Patient_info.parquet')
df2

,Patient_ID,Sex,Age,Age_when_diagnosed,Weight,Height,Number_of_days_with_measures,Number_of_measurements
139,2,M,29,26,95.0,182.0,176,48954
14,3,M,27,12,65.2,173.0,182,50407
210,5,M,61,13,84.0,177.8,141,38566
62,7,F,36,12,63.0,164.0,190,52160
159,8,F,48,7,62.5,170.2,183,48081
...,...,...,...,...,...,...,...,...
147,289,M,30,5,101.8,179.0,1,132
56,290,M,39,22,88.5,179.0,176,44862
72,291,F,25,10,73.0,163.0,161,42855
201,292,F,49,3,59.0,163.0,176,46634
6,293,F,35,7,64.4,170.0,176,47310

In [4]:
df3 = pd.read_parquet('Patient_info-.parquet')
df3

     Patient_ID Sex  Age  Number_of_days_with_measures  Number_of_measurements
139           2   M   29                           176                   48954
14            3   M   27                           182                   50407
210           5   M   61                           141                   38566
62            7   F   36                           190                   52160
159           8   F   48                           183                   48081
..          ...  ..  ...                           ...                     ...
177         288   M   44                           177                   47010
56          290   M   39                           176                   44862
72          291   F   25                           161                   42855
201         292   F   49                           176                   46634
6           293   F   35                           176                   47310

[223 rows x 5 columns]