Compare the different results of the different experimentation of the general result

In [1]:
import pandas as pd
import os

In [26]:
df_new_result_1 = pd.read_csv('results/performance/metrics_performance_by_range_CNN_Fold1_Exclusive_Zone_A_and_E_and_D.csv')
df_new_result_2 = pd.read_csv('results/performance/metrics_performance_by_range_CNN_Fold1_H4.csv')

In [27]:
df_new_result_1

    Range      A      B     C      D     E  A + B   RMSE      MSE    MAE  MAPE
0  ENTIRE  60.08  33.03  0.65   6.13  0.11  93.11  43.32  1876.40  31.82  0.22
1   TBR_2   2.03   0.00  0.00  96.28  1.70   2.03  52.57  2763.57  46.88  0.97
2   TBR_1   1.62   0.00  0.00  96.09  2.29   1.62  48.79  2380.95  41.90  0.68
3     TIR  59.62  39.41  0.97   0.00  0.00  99.03  34.52  1191.91  25.62  0.22
4   TAR_1  72.37  25.39  0.29   1.94  0.01  97.76  43.42  1884.92  32.09  0.15
5   TAR_2  61.49  30.13  0.11   8.26  0.00  91.62  69.91  4887.07  56.43  0.18

# Find differences Original VS New

In [28]:
df_new_result_1.columns

Index(['Range', 'A', 'B', 'C', 'D', 'E', 'A + B', 'RMSE', 'MSE', 'MAE',
       'MAPE'],
      dtype='object')

In [29]:
df_diff = df_new_result_1[['A', 'B', 'C', 'D', 'E', 'A + B', 'RMSE', 'MSE', 'MAE', 'MAPE']] - df_new_result_2[['A', 'B', 'C', 'D', 'E', 'A + B', 'RMSE', 'MSE', 'MAE', 'MAPE']]
df_diff

     A     B     C     D     E  A + B  RMSE  MSE  MAE  MAPE
0  0.0  0.28  0.01 -0.28 -0.01   0.28   0.0  0.0  0.0   0.0
1  0.0  0.00  0.00  0.00  0.00   0.00   0.0  0.0  0.0   0.0
2  0.0  0.00  0.00  0.00  0.00   0.00   0.0  0.0  0.0   0.0
3  0.0  0.46  0.02 -0.47 -0.01   0.46   0.0  0.0  0.0   0.0
4  0.0  0.00  0.00  0.00  0.00   0.00   0.0  0.0  0.0   0.0
5  0.0  0.00  0.00  0.00  0.00   0.00   0.0  0.0  0.0   0.0

In [25]:
df_diff.describe()

         A    B         C    D         E  A + B  RMSE  MSE  MAE  MAPE
count  6.0  6.0  6.000000  6.0  6.000000    6.0   6.0  6.0  6.0   6.0
mean   0.0  0.0  0.005000  0.0 -0.003333    0.0   0.0  0.0  0.0   0.0
std    0.0  0.0  0.008367  0.0  0.005164    0.0   0.0  0.0  0.0   0.0
min    0.0  0.0  0.000000  0.0 -0.010000    0.0   0.0  0.0  0.0   0.0
25%    0.0  0.0  0.000000  0.0 -0.007500    0.0   0.0  0.0  0.0   0.0
50%    0.0  0.0  0.000000  0.0  0.000000    0.0   0.0  0.0  0.0   0.0
75%    0.0  0.0  0.007500  0.0  0.000000    0.0   0.0  0.0  0.0   0.0
max    0.0  0.0  0.020000  0.0  0.000000    0.0   0.0  0.0  0.0   0.0